CREATE TABLE trail_imaginary(
                                id INT AUTO_INCREMENT PRIMARY KEY,
                                name VARCHAR(100) NOT NULL);

INSERT INTO trail_imaginary (name) VALUES
                                       ('Mystic Trail'),
                                       ('Enchanted Path'),
                                       ('Whispering Woods'),
                                       ('Hidden Valley'),
                                       ('Secret Garden'),
                                       ('Ethereal Summit'),
                                       ('Magical Meadow'),
                                       ('Twilight Trail'),
                                       ('Majestic Peaks'),
                                       ('Dreamy Canyon'),
                                       ('Starlight Ridge'),
                                       ('Serenity Lake'),
                                       ('Fantasy Falls'),
                                       ('Tranquil Brook'),
                                       ('Mystical Marsh'),
                                       ('Moonlit Path'),
                                       ('Radiant River'),
                                       ('Glimmering Glade'),
                                       ('Mystery Mountain'),
                                       ('Blissful Beach'),
                                       ('Sunrise Slope'),
                                       ('Sunset Hill'),
                                       ('Glowing Grotto'),
                                       ('Echoing Forest'),
                                       ('Aurora Trail'),
                                       ('Whimsical Waterfall'),
                                       ('Peaceful Plateau'),
                                       ('Jubilant Jungle'),
                                       ('Celestial Cliffs'),
                                       ('Fairyland Forest');
INSERT INTO trail_imaginary (name) VALUES
                                       ('Whispering Wind Trail'),
                                       ('Enchanted Forest Path'),
                                       ('Mystic Mountain Trail'),
                                       ('Eternal Twilight Path'),
                                       ('Sapphire Stream Trail'),
                                       ('Golden Sunset Ridge'),
                                       ('Emerald Valley Trail'),
                                       ('Hidden Oasis Path'),
                                       ('Cascade Canyon Trail'),
                                       ('Silver Moonlight Path'),
                                       ('Rainbow River Trail'),
                                       ('Dreamy Desert Path'),
                                       ('Soothing Sound Trail'),
                                       ('Crystal Clear Lake Trail'),
                                       ('Gentle Breeze Path'),
                                       ('Tranquil Treetop Trail'),
                                       ('Velvet Valley Path'),
                                       ('Majestic Mirage Trail'),
                                       ('Echoing Evergreen Path'),
                                       ('Harmony Hills Trail'),
                                       ('Royal Rainforest Path'),
                                       ('Celestial Summit Trail'),
                                       ('Sparkling Seashore Path'),
                                       ('Luminous Lagoon Trail'),
                                       ('Serene Snowfall Path'),
                                       ('Whispering Waterfall Trail'),
                                       ('Mystical Meadow Path'),
                                       ('Twinkling Twilight Trail'),
                                       ('Vibrant Vista Path'),
                                       ('Flourishing Forest Trail');
INSERT INTO trail_imaginary (name) VALUES
                                       ('Sun-kissed Summit Trail'),
                                       ('Moonlit Meadows Path'),
                                       ('Dewdrop Dale Trail'),
                                       ('Wildflower Wonderland Path'),
                                       ('Starlit Skyline Trail'),
                                       ('Foggy Forest Path'),
                                       ('Echo Canyon Trail'),
                                       ('Sunset Serenity Path'),
                                       ('Golden Grove Trail'),
                                       ('Silver Stream Path'),
                                       ('Rainbow Ridge Trail'),
                                       ('Misty Mountain Path'),
                                       ('Sunrise Slope Trail'),
                                       ('Moonbeam Meadow Path'),
                                       ('Frosty Falls Trail'),
                                       ('Lush Lagoon Path'),
                                       ('Whispering Willow Trail'),
                                       ('Glimmering Glade Path'),
                                       ('Twilight Terrace Trail'),
                                       ('Tranquil Tide Path'),
                                       ('Secret Garden Trail'),
                                       ('Crimson Cliffs Path'),
                                       ('Azure Abyss Trail'),
                                       ('Gentle Glacial Path'),
                                       ('Silent Snowdrift Trail'),
                                       ('Enchanted Estuary Path'),
                                       ('Majestic Mesa Trail'),
                                       ('Soothing Sands Path'),
                                       ('Vivid Vista Trail');
INSERT INTO trail_imaginary (name) VALUES
                                       ('Emerald Enclave Trail'),
                                       ('Whispering Winds Path'),
                                       ('Cascade Canyon Trail'),
                                       ('Sapphire Springs Path'),
                                       ('Ethereal Elevation Trail'),
                                       ('Mystic Moonlight Path'),
                                       ('Serene Summit Trail'),
                                       ('Tropical Tranquility Path'),
                                       ('Whimsical Waterfall Trail'),
                                       ('Golden Gate Trail'),
                                       ('Amber Archway Path'),
                                       ('Vibrant Valley Trail'),
                                       ('Harmony Hill Path'),
                                       ('Majestic Maple Trail'),
                                       ('Sapphire Serenity Path'),
                                       ('Enchanted Eden Trail'),
                                       ('Radiant Rainbow Path'),
                                       ('Majestic Mountain Trail'),
                                       ('Mystical Meadow Path'),
                                       ('Tranquil Timber Trail'),
                                       ('Lunar Lake Path'),
                                       ('Whispering Woods Trail'),
                                       ('Golden Grove Path'),
                                       ('Celestial Crest Trail'),
                                       ('Sunburst Summit Path'),
                                       ('Peaceful Pines Trail'),
                                       ('Ethereal Expanse Path'),
                                       ('Moonlit Mesa Trail'),
                                       ('Sunrise Sanctuary Path'),
                                       ('Starry Sky Trail');
INSERT INTO trail_imaginary (name) VALUES
                                       ('Tranquil Terrace Trail'),
                                       ('Golden Gorge Path'),
                                       ('Whispering Willow Trail'),
                                       ('Mystic Mirage Path'),
                                       ('Enchanted Echo Trail'),
                                       ('Sapphire Springs Trail'),
                                       ('Majestic Meadow Path'),
                                       ('Celestial Cascade Trail'),
                                       ('Harmonious Haven Path'),
                                       ('Serene Summit Trail'),
                                       ('Whimsical Waters Path'),
                                       ('Radiant Ridge Trail'),
                                       ('Emerald Enchantment Path'),
                                       ('Lunar Lagoon Trail'),
                                       ('Golden Glade Path'),
                                       ('Twilight Trail'),
                                       ('Crimson Canyon Path'),
                                       ('Vibrant Vista Trail'),
                                       ('Mystical Moss Path'),
                                       ('Starlight Trail'),
                                       ('Whispering Woods Trail'),
                                       ('Tranquil Timber Path'),
                                       ('Whispering Wind Trail'),
                                       ('Ethereal Escarpment Path'),
                                       ('Tranquil Terrace Trail'),
                                       ('Lush Landscape Path'),
                                       ('Majestic Mirage Trail'),
                                       ('Celestial Crest Path'),
                                       ('Mystic Meadow Trail'),
                                       ('Sunrise Sanctuary Path');
INSERT INTO trail_imaginary (name) VALUES
                                       ('Sunset Serenity Trail'),
                                       ('Emerald Echo Path'),
                                       ('Golden Grove Trail'),
                                       ('Crimson Crest Path'),
                                       ('Sapphire Sanctuary Trail'),
                                       ('Whispering Willow Path'),
                                       ('Tranquil Twilight Trail'),
                                       ('Mystical Mountain Path'),
                                       ('Enchanted Eden Trail'),
                                       ('Radiant Rainbow Path'),
                                       ('Harmonious Hike Trail'),
                                       ('Celestial Summit Path'),
                                       ('Twilight Tranquility Trail'),
                                       ('Whimsical Waterfall Path'),
                                       ('Sapphire Skyline Trail'),
                                       ('Golden Glade Path'),
                                       ('Crimson Canyon Trail'),
                                       ('Vibrant Valley Path'),
                                       ('Mystical Moonlight Trail'),
                                       ('Ethereal Echo Path'),
                                       ('Tranquil Timber Trail'),
                                       ('Whispering Winds Path'),
                                       ('Lush Lagoon Trail'),
                                       ('Majestic Meadow Path'),
                                       ('Sunrise Splendor Trail'),
                                       ('Tranquil Twilight Path'),
                                       ('Whispering Waterfall Trail'),
                                       ('Mystic Mountain Path'),
                                       ('Ethereal Essence Trail'),
                                       ('Harmonious Haven Path');
INSERT INTO trail_imaginary (name) VALUES
                                       ('Golden Glade Trail'),
                                       ('Sunrise Summit Path'),
                                       ('Crimson Canyon Trail'),
                                       ('Whispering Woods Path'),
                                       ('Emerald Enclave Trail'),
                                       ('Mystic Marsh Path'),
                                       ('Tranquil Treetop Trail'),
                                       ('Sapphire Stream Path'),
                                       ('Harmonious Highlands Trail'),
                                       ('Whimsical Waterfall Trail'),
                                       ('Sunset Sanctuary Path'),
                                       ('Celestial Cliff Trail'),
                                       ('Ethereal Echoes Path'),
                                       ('Twilight Trail'),
                                       ('Majestic Meadow Trail'),
                                       ('Enchanted Forest Path'),
                                       ('Vibrant Valley Trail'),
                                       ('Tranquil Timber Trail'),
                                       ('Whispering Willow Trail'),
                                       ('Golden Grove Path'),
                                       ('Crimson Crest Trail'),
                                       ('Emerald Echo Path'),
                                       ('Sapphire Serenity Trail'),
                                       ('Mystical Moonlight Path'),
                                       ('Radiant Rainbow Trail'),
                                       ('Whispering Winds Path'),
                                       ('Tranquil Twilight Path'),
                                       ('Lush Lagoon Trail'),
                                       ('Majestic Mountain Trail'),
                                       ('Ethereal Essence Path');
INSERT INTO trail_imaginary (name) VALUES
                                       ('Serene Summit Trail'),
                                       ('Azure Adventure Path'),
                                       ('Harmony Hill Trail'),
                                       ('Golden Glade Path'),
                                       ('Mystic Meadow Trail'),
                                       ('Tranquil Timber Path'),
                                       ('Whispering Willow Trail'),
                                       ('Celestial Cliff Path'),
                                       ('Sapphire Stream Trail'),
                                       ('Whimsical Waterfall Path'),
                                       ('Sunset Sanctuary Trail'),
                                       ('Ethereal Echoes Path'),
                                       ('Twilight Trail'),
                                       ('Whispering Winds Trail'),
                                       ('Tranquil Treetop Path'),
                                       ('Radiant Rainbow Trail'),
                                       ('Harmonious Highlands Path'),
                                       ('Crimson Canyon Trail'),
                                       ('Emerald Enclave Path'),
                                       ('Enchanted Forest Trail'),
                                       ('Vibrant Valley Path'),
                                       ('Sunrise Summit Trail'),
                                       ('Crimson Crest Path'),
                                       ('Emerald Echo Trail'),
                                       ('Mystical Moonlight Path'),
                                       ('Tranquil Twilight Trail'),
                                       ('Whispering Woods Path'),
                                       ('Majestic Mountain Path'),
                                       ('Ethereal Essence Trail'),
                                       ('Lush Lagoon Path');
INSERT INTO trail_imaginary (name) VALUES
                                       ('Sunny Slope Trail'),
                                       ('Breezy Bluff Path'),
                                       ('Whistling Willow Trail'),
                                       ('Crystal Clear Creek Path'),
                                       ('Emerald Evergreen Trail'),
                                       ('Golden Grove Path'),
                                       ('Serene Stream Trail'),
                                       ('Majestic Mountain Trail'),
                                       ('Wildflower Way'),
                                       ('Peaceful Pine Trail'),
                                       ('Whispering Waters Path'),
                                       ('Tranquil Terrace Trail'),
                                       ('Cascading Falls Trail'),
                                       ('Rustic Ridge Path'),
                                       ('Misty Meadow Trail'),
                                       ('Sunshine Summit Trail'),
                                       ('Echoing Forest Trail'),
                                       ('Hidden Hollow Path'),
                                       ('Peaceful Pond Trail'),
                                       ('Rocky Ridge Path'),
                                       ('Harmony Hollow Trail'),
                                       ('Shady Grove Path'),
                                       ('Soothing Stream Trail'),
                                       ('Babbling Brook Path'),
                                       ('Rugged Ravine Trail'),
                                       ('Whispering Woods Trail'),
                                       ('Mossy Glen Path'),
                                       ('Falling Leaves Trail'),
                                       ('Crisp Creek Path'),
                                       ('Tranquil Trail');
INSERT INTO trail_imaginary (name) VALUES
                                       ('Golden Gate Trail'),
                                       ('Pacific Crest Trail'),
                                       ('Grand Canyon Trail'),
                                       ('Yosemite Valley Trail'),
                                       ('Rocky Mountain Trail'),
                                       ('Great Smoky Mountains Trail'),
                                       ('Zion Narrows Trail'),
                                       ('Appalachian Trail'),
                                       ('Yellowstone Trail'),
                                       ('Glacier National Park Trail'),
                                       ('Everglades Trail'),
                                       ('Acadia National Park Trail'),
                                       ('Arches National Park Trail'),
                                       ('Canyonlands Trail'),
                                       ('Death Valley Trail'),
                                       ('Sequoia Trail'),
                                       ('Joshua Tree Trail'),
                                       ('Bryce Canyon Trail'),
                                       ('Mount Rainier Trail'),
                                       ('Redwood Trail'),
                                       ('Denali Trail'),
                                       ('Olympic National Park Trail'),
                                       ('Crater Lake Trail'),
                                       ('Grand Teton Trail'),
                                       ('Hawaii Volcanoes Trail'),
                                       ('Badlands Trail'),
                                       ('Saguaro Trail'),
                                       ('Great Sand Dunes Trail'),
                                       ('Carlsbad Caverns Trail'),
                                       ('Shenandoah National Park Trail');
INSERT INTO trail_imaginary (name) VALUES
                                       ('Zion Angels Landing Trail'),
                                       ('Mount Whitney Trail'),
                                       ('Havasu Falls Trail'),
                                       ('Half Dome Trail'),
                                       ('The Wave Trail'),
                                       ('Antelope Canyon Trail'),
                                       ('Horseshoe Bend Trail'),
                                       ('Bryce Canyon Queens Garden Trail'),
                                       ('Devils Bridge Trail'),
                                       ('Delicate Arch Trail'),
                                       ('Rim-to-Rim Trail'),
                                       ('Bright Angel Trail'),
                                       ('Hiking in the Smoky Mountains'),
                                       ('Appalachian Mountain Trail'),
                                       ('Pikes Peak Trail'),
                                       ('Yosemite Falls Trail'),
                                       ('John Muir Trail'),
                                       ('Machu Picchu Trail'),
                                       ('Inca Trail'),
                                       ('Kilimanjaro Trail'),
                                       ('Everest Base Camp Trail'),
                                       ('Kungsleden Trail'),
                                       ('West Coast Trail'),
                                       ('Long Trail'),
                                       ('Continental Divide Trail'),
                                       ('Ice Age Trail'),
                                       ('North Country Trail'),
                                       ('Tahoe Rim Trail'),
                                       ('Pacific Northwest Trail'),
                                       ('Florida Trail');
INSERT INTO trail_imaginary (name) VALUES
                                       ('Grand Canyon Rim Trail'),
                                       ('Yellowstone Grand Loop Trail'),
                                       ('Great Wall of China Hike'),
                                       ('Torres del Paine Circuit'),
                                       ('Kalalau Trail'),
                                       ('Kauai Napali Coast Trail'),
                                       ('Mount Kilimanjaro Lemosho Route'),
                                       ('Annapurna Circuit Trek'),
                                       ('Patagonia W Trek'),
                                       ('Mount Fuji Yoshida Trail'),
                                       ('Glacier National Park Highline Trail'),
                                       ('Denali National Park Savage Alpine Trail'),
                                       ('Tongariro Alpine Crossing'),
                                       ('Southwest Coast Path'),
                                       ('Norway Trolltunga Hike'),
                                       ('Camino de Santiago'),
                                       ('Cinque Terre Coastal Trail'),
                                       ('Salkantay Trek to Machu Picchu'),
                                       ('Mount Cook Hooker Valley Track'),
                                       ('The Appalachian Trail'),
                                       ('Everest Base Camp Trek'),
                                       ('Annapurna Base Camp Trek'),
                                       ('Baltoro Glacier Concordia Trek'),
                                       ('Glymur Waterfall Hike'),
                                       ('Switzerland Haute Route'),
                                       ('Scotland West Highland Way'),
                                       ('Mount Rainier Wonderland Trail'),
                                       ('John Muir Trail'),
                                       ('Mount Roraima Trek');
INSERT INTO trail_imaginary (name) VALUES
                                       ('Inca Trail to Machu Picchu'),
                                       ('Zion Narrows Hike'),
                                       ('Yosemite Half Dome Hike'),
                                       ('Angel\'s Landing Trail'),
                                       ('Havasu Falls Hike'),
                                       ('Sahara Desert Trek'),
                                       ('Grand Teton Cascade Canyon Trail'),
                                       ('Acadia National Park Precipice Trail'),
                                       ('Olympic National Park Hoh River Trail'),
                                       ('New Zealand Routeburn Track'),
                                       ('Colorado Maroon Bells Trail'),
                                       ('Japan Nakasendo Trail'),
                                       ('Pacific Crest Trail'),
                                       ('Arches National Park Delicate Arch Trail'),
                                       ('Great Smoky Mountains Alum Cave Trail'),
                                       ('Death Valley Badwater Basin Trail'),
                                       ('Antelope Canyon Hike'),
                                       ('Himalayas Langtang Valley Trek'),
                                       ('Everglades National Park Anhinga Trail'),
                                       ('Arctic Circle Trail'),
                                       ('Tongariro Northern Circuit'),
                                       ('Mount Elbert Trail'),
                                       ('Hawaii Volcanoes National Park Crater Rim Trail'),
                                       ('Patagonia Fitz Roy Trek'),
                                       ('Yosemite Glacier Point Trail'),
                                       ('Mount Cook Sealy Tarns Track'),
                                       ('Pacific Crest Trail'),
                                       ('Torres del Paine O Circuit'),
                                       ('Pamir Mountains Trek'),
                                       ('Iceland Laugavegur Trail');
INSERT INTO trail_imaginary (name) VALUES
                                       ('Everest Base Camp Trek'),
                                       ('Machu Picchu Salkantay Trek'),
                                       ('Trolltunga Hike'),
                                       ('Kilimanjaro Lemosho Route'),
                                       ('Great Wall of China Trek'),
                                       ('Mount Fuji Climbing Trail'),
                                       ('Cinque Terre Coastal Trail'),
                                       ('Zion Observation Point Trail'),
                                       ('Denali National Park Trail'),
                                       ('Sahara Desert Camel Trek'),
                                       ('Peru Ausangate Trek'),
                                       ('Appalachian Trail'),
                                       ('Yellowstone National Park Grand Canyon of the Yellowstone'),
                                       ('Pamukkale Hierapolis Archaeological Site'),
                                       ('Lake Louise Tea House Trail'),
                                       ('Swiss Alps Eiger Trail'),
                                       ('Torres del Paine W Trek'),
                                       ('Patagonia Torres del Paine Circuit'),
                                       ('Inca Trail to Machu Picchu'),
                                       ('Sedona Cathedral Rock Trail'),
                                       ('Havasu Falls Hike'),
                                       ('Haleakalā National Park Sliding Sands Trail'),
                                       ('Redwood National and State Parks Tall Trees Trail'),
                                       ('Grand Canyon Bright Angel Trail'),
                                       ('Scotland West Highland Way'),
                                       ('Nepal Annapurna Circuit Trek'),
                                       ('California John Muir Trail'),
                                       ('Antelope Canyon Upper Antelope Canyon Trail'),
                                       ('Mongolia Gobi Desert Trek');
INSERT INTO trail_imaginary (name) VALUES
                                       ('Yosemite National Park Half Dome Trail'),
                                       ('Switzerland Jungfrau Region Trail'),
                                       ('New Zealand Milford Track'),
                                       ('Arizona Wave Trail'),
                                       ('Norway Preikestolen Hike'),
                                       ('Canada Banff National Park Trail'),
                                       ('Australia Great Ocean Walk'),
                                       ('Italy Dolomites Alta Via 1'),
                                       ('Scotland Isle of Skye Trail'),
                                       ('Japan Nakasendo Trail'),
                                       ('Austria Lechweg Trail'),
                                       ('Spain Camino de Santiago'),
                                       ('Thailand Khao Sok National Park Trail'),
                                       ('Alaska Chilkoot Trail'),
                                       ('Iceland Laugavegur Trail'),
                                       ('Greece Samaria Gorge Trail'),
                                       ('France Mont Blanc Circuit'),
                                       ('Vietnam Sapa Valley Trek'),
                                       ('Peru Choquequirao Trek'),
                                       ('South Africa Drakensberg Grand Traverse'),
                                       ('Chile Valle del Cochamó Trail'),
                                       ('Indonesia Mount Rinjani Trek'),
                                       ('Portugal Rota Vicentina Trail'),
                                       ('United Kingdom Coast to Coast Trail'),
                                       ('Brazil Chapada Diamantina Trek'),
                                       ('China Zhangjiajie National Forest Park Trail'),
                                       ('Kenya Mount Kenya Summit Circuit'),
                                       ('Germany Rheinsteig Trail'),
                                       ('India Markha Valley Trek');
INSERT INTO trail_imaginary (name) VALUES
                                       ('Nepal Everest Base Camp Trek'),
                                       ('Sweden Kungsleden Trail'),
                                       ('Finland Karhunkierros Trail'),
                                       ('Russia Lake Baikal Trail'),
                                       ('Mexico Copper Canyon Trail'),
                                       ('Argentina Fitz Roy Trek'),
                                       ('Ireland Wicklow Way Trail'),
                                       ('Croatia Plitvice Lakes National Park Trail'),
                                       ('South Korea Seoraksan National Park Trail'),
                                       ('Switzerland Bernese Oberland Trail'),
                                       ('New Zealand Routeburn Track'),
                                       ('Australia Larapinta Trail'),
                                       ('Italy Cinque Terre Coastal Trail'),
                                       ('Scotland West Highland Way'),
                                       ('Japan Kumano Kodo Pilgrimage Trail'),
                                       ('Austria Alpe-Adria Trail'),
                                       ('Spain GR 20 Corsica Trail'),
                                       ('Thailand Inthanon Mountain Trail'),
                                       ('Canada West Coast Trail'),
                                       ('Iceland Fimmvörðuháls Pass Trail'),
                                       ('Greece Mount Olympus Trail'),
                                       ('France Tour du Mont Blanc'),
                                       ('Vietnam Ha Giang Loop Trail'),
                                       ('Peru Inca Trail to Machu Picchu'),
                                       ('South Africa Otter Trail'),
                                       ('Chile Torres del Paine W Trek'),
                                       ('Indonesia Komodo Island Trail'),
                                       ('Portugal Fishermen''s Trail'),
                                       ('United Kingdom Pennine Way'),
                                       ('Brazil Pedra da Gávea Trail');
INSERT INTO trail_imaginary (name) VALUES
                                       ('Norway Trolltunga Trail'),
                                       ('United States Appalachian Trail'),
                                       ('China Great Wall Trail'),
                                       ('Kenya Mount Kenya Trail'),
                                       ('Nepal Annapurna Circuit Trek'),
                                       ('Germany Rennsteig Trail'),
                                       ('Argentina Perito Moreno Glacier Trail'),
                                       ('Sweden Sarek National Park Trail'),
                                       ('Italy Dolomites Alta Via 1 Trail'),
                                       ('Spain Camino de Santiago Trail'),
                                       ('Canada Chilkoot Trail'),
                                       ('New Zealand Milford Track'),
                                       ('Australia Overland Track'),
                                       ('Russia Trans-Siberian Trail'),
                                       ('United States Pacific Crest Trail'),
                                       ('Chile Atacama Desert Trail'),
                                       ('Brazil Chapada Diamantina Trail'),
                                       ('Scotland Great Glen Way'),
                                       ('France GR20 Corsica Trail'),
                                       ('Ireland Dingle Way Trail'),
                                       ('Japan Nakasendo Trail'),
                                       ('Switzerland Swiss National Park Trail'),
                                       ('Peru Salkantay Trek'),
                                       ('Vietnam Ho Chi Minh Trail'),
                                       ('China Tiger Leaping Gorge Trail'),
                                       ('South Africa Drakensberg Grand Traverse Trail'),
                                       ('United States Zion Narrows Trail'),
                                       ('Canada Juan de Fuca Trail'),
                                       ('Nepal Langtang Valley Trail'),
                                       ('Australia Cape to Cape Track');
INSERT INTO trail_imaginary (name) VALUES
                                       ('Norway Fjord Trail'),
                                       ('United States Grand Canyon Trail'),
                                       ('Canada Banff National Park Trail'),
                                       ('New Zealand Routeburn Track'),
                                       ('Australia Larapinta Trail'),
                                       ('Scotland West Highland Way'),
                                       ('France Tour du Mont Blanc Trail'),
                                       ('Peru Inca Trail'),
                                       ('Switzerland Eiger Trail'),
                                       ('Italy Cinque Terre Trail'),
                                       ('Spain GR7 Trail'),
                                       ('Japan Kumano Kodo Trail'),
                                       ('Nepal Everest Base Camp Trek'),
                                       ('South Africa Otter Trail'),
                                       ('Patagonia Torres del Paine Trail'),
                                       ('Ireland Wicklow Way Trail'),
                                       ('China Huangshan Trail'),
                                       ('Vietnam Sapa Valley Trail'),
                                       ('Thailand Chiang Mai Trail'),
                                       ('Brazil Rio de Janeiro Coastal Trail'),
                                       ('Argentina Patagonia Glacier Trail'),
                                       ('Alaska Denali National Park Trail'),
                                       ('Hawaii Kalalau Trail'),
                                       ('Arizona Havasu Falls Trail'),
                                       ('Utah Bryce Canyon Trail'),
                                       ('Washington Olympic National Park Trail'),
                                       ('California John Muir Trail'),
                                       ('Oregon Pacific Crest Trail'),
                                       ('New York Adirondack High Peaks Trail');
INSERT INTO trail_imaginary (name) VALUES
                                       ('Norway Trolltunga Trail'),
                                       ('United States Appalachian Trail'),
                                       ('Canada West Coast Trail'),
                                       ('New Zealand Kepler Track'),
                                       ('Australia Overland Track'),
                                       ('Scotland Rob Roy Way'),
                                       ('France GR20 Trail'),
                                       ('Peru Choquequirao Trail'),
                                       ('Switzerland Bernese Oberland Trail'),
                                       ('Italy Dolomites Alta Via 1 Trail'),
                                       ('Spain Camino de Santiago Trail'),
                                       ('Japan Nakasendo Trail'),
                                       ('Nepal Annapurna Circuit Trail'),
                                       ('South Africa Drakensberg Grand Traverse Trail'),
                                       ('Patagonia Cerro Torre Trail'),
                                       ('Ireland Dingle Way Trail'),
                                       ('China Tiger Leaping Gorge Trail'),
                                       ('Vietnam Ho Chi Minh Trail'),
                                       ('Thailand Doi Inthanon Trail'),
                                       ('Brazil Chapada Diamantina Trail'),
                                       ('Argentina Mount Fitz Roy Trail'),
                                       ('Alaska Resurrection Pass Trail'),
                                       ('Hawaii Na Pali Coast Trail'),
                                       ('Arizona Grand Canyon Rim-to-Rim Trail'),
                                       ('Utah Zion Narrows Trail'),
                                       ('Washington Wonderland Trail'),
                                       ('California Lost Coast Trail'),
                                       ('Oregon Timberline Trail'),
                                       ('New York Catskill Mountains Trail');
INSERT INTO trail_imaginary (name) VALUES
                                       ('Norway Lofoten Islands Trail'),
                                       ('United States Pacific Crest Trail'),
                                       ('Canada Banff National Park Trail'),
                                       ('New Zealand Milford Track'),
                                       ('Australia Larapinta Trail'),
                                       ('Scotland West Highland Way'),
                                       ('France Tour du Mont Blanc Trail'),
                                       ('Peru Inca Trail'),
                                       ('Switzerland Tour du Mont Blanc Trail'),
                                       ('Italy Cinque Terre Trail'),
                                       ('Spain GR 11 Trail'),
                                       ('Japan Kumano Kodo Trail'),
                                       ('Nepal Everest Base Camp Trek'),
                                       ('South Africa Otter Trail'),
                                       ('Patagonia Torres del Paine Trail'),
                                       ('Ireland Wicklow Way Trail'),
                                       ('China Mount Huashan Trail'),
                                       ('Vietnam Sapa Valley Trail'),
                                       ('Thailand Phu Kradueng Trail'),
                                       ('Brazil Serra da Mantiqueira Trail'),
                                       ('Argentina Patagonian Lake District Trail'),
                                       ('Alaska Chilkoot Trail'),
                                       ('Hawaii Kalalau Trail'),
                                       ('Arizona Havasu Falls Trail'),
                                       ('Utah Bryce Canyon Trail'),
                                       ('Washington Olympic Coast Trail'),
                                       ('California John Muir Trail'),
                                       ('Oregon Eagle Creek Trail'),
                                       ('New York Adirondack High Peaks Trail');
INSERT INTO trail_imaginary (name) VALUES
                                       ('Colorado Continental Divide Trail'),
                                       ('Montana Glacier National Park Trail'),
                                       ('Wyoming Teton Crest Trail'),
                                       ('Idaho Sawtooth Wilderness Trail'),
                                       ('Utah Zion Narrows Trail'),
                                       ('Nevada Ruby Crest Trail'),
                                       ('Arizona Grand Canyon Rim-to-Rim Trail'),
                                       ('New Mexico Gila Wilderness Trail'),
                                       ('Texas Big Bend National Park Trail'),
                                       ('California Lost Coast Trail'),
                                       ('Washington Wonderland Trail'),
                                       ('Oregon Pacific Crest Trail'),
                                       ('Alaska Denali National Park Trail'),
                                       ('Hawaii Kalalau Valley Trail'),
                                       ('Florida Florida Trail'),
                                       ('North Carolina Appalachian Trail'),
                                       ('Georgia Appalachian Trail'),
                                       ('Virginia Appalachian Trail'),
                                       ('Tennessee Appalachian Trail'),
                                       ('Maine Appalachian Trail'),
                                       ('Pennsylvania Appalachian Trail'),
                                       ('New Jersey Appalachian Trail'),
                                       ('New York Appalachian Trail'),
                                       ('Connecticut Appalachian Trail'),
                                       ('Massachusetts Appalachian Trail'),
                                       ('Vermont Appalachian Trail'),
                                       ('New Hampshire Appalachian Trail'),
                                       ('Ohio Appalachian Trail'),
                                       ('West Virginia Appalachian Trail'),
                                       ('Maryland Appalachian Trail');
INSERT INTO trail_imaginary (name) VALUES
                                       ('Colorado Four Pass Loop Trail'),
                                       ('Montana Beartooth Loop Trail'),
                                       ('Wyoming Wind River Range Trail'),
                                       ('Idaho White Clouds Loop Trail'),
                                       ('Utah Bryce Canyon Peekaboo Loop Trail'),
                                       ('Nevada Lake Tahoe Rim Trail'),
                                       ('Arizona Havasu Falls Trail'),
                                       ('New Mexico Bandelier National Monument Trail'),
                                       ('Texas Guadalupe Mountains National Park Trail'),
                                       ('California John Muir Trail'),
                                       ('Washington Olympic Coast Trail'),
                                       ('Oregon Eagle Cap Wilderness Trail'),
                                       ('Alaska Harding Icefield Trail'),
                                       ('Hawaii Kalalau Trail'),
                                       ('Florida Ocala National Forest Trail'),
                                       ('North Carolina Linville Gorge Trail'),
                                       ('Georgia Blood Mountain Loop Trail'),
                                       ('Virginia Shenandoah National Park Trail'),
                                       ('Tennessee Great Smoky Mountains National Park Trail'),
                                       ('Maine Acadia National Park Trail'),
                                       ('Pennsylvania Laurel Highlands Trail'),
                                       ('New Jersey Delaware Water Gap Trail'),
                                       ('New York Catskill Mountains Trail'),
                                       ('Connecticut Sleeping Giant State Park Trail'),
                                       ('Massachusetts Mount Greylock Trail'),
                                       ('Vermont Camel\'s Hump Trail'),
                                       ('New Hampshire Franconia Ridge Trail'),
                                       ('Ohio Cuyahoga Valley National Park Trail'),
                                       ('West Virginia Dolly Sods Wilderness Trail'),
                                       ('Maryland Appalachian Trail');
INSERT INTO trail_imaginary (name) VALUES
                                       ('Michigan Porcupine Mountains Trail'),
                                       ('Wisconsin Ice Age National Scenic Trail'),
                                       ('Minnesota Superior Hiking Trail'),
                                       ('Iowa Effigy Mounds National Monument Trail'),
                                       ('Missouri Ozark Trail'),
                                       ('Arkansas Ouachita National Recreation Trail'),
                                       ('Louisiana Kisatchie National Forest Trail'),
                                       ('Mississippi Natchez Trace Parkway Trail'),
                                       ('Alabama Pinhoti National Recreation Trail'),
                                       ('Kentucky Red River Gorge Trail'),
                                       ('Indiana Knobstone Trail'),
                                       ('Illinois Shawnee National Forest Trail'),
                                       ('Iowa Great River Road Trail'),
                                       ('Kansas Tallgrass Prairie National Preserve Trail'),
                                       ('Nebraska Niobrara National Scenic River Trail'),
                                       ('South Dakota Black Elk Peak Trail'),
                                       ('North Dakota Maah Daah Hey Trail'),
                                       ('Montana Continental Divide Trail'),
                                       ('Wyoming Teton Crest Trail'),
                                       ('Colorado Colorado Trail'),
                                       ('New Mexico Gila Wilderness Trail'),
                                       ('Texas Big Bend National Park Trail'),
                                       ('Arizona Grand Canyon Rim-to-Rim Trail'),
                                       ('Nevada Valley of Fire State Park Trail'),
                                       ('Utah Zion National Park Trail'),
                                       ('California Pacific Crest Trail'),
                                       ('Washington Wonderland Trail'),
                                       ('Oregon Pacific Crest Trail'),
                                       ('Alaska Chilkoot Trail'),
                                       ('Hawaii Haleakala Crater Trail');
INSERT INTO trail_imaginary (name) VALUES
                                       ('New Hampshire White Mountains Trail'),
                                       ('Vermont Long Trail'),
                                       ('Maine Appalachian Trail'),
                                       ('Massachusetts Mount Greylock Trail'),
                                       ('Connecticut Appalachian Trail'),
                                       ('Rhode Island North-South Trail'),
                                       ('New York Adirondack High Peaks Trail'),
                                       ('New Jersey Appalachian Trail'),
                                       ('Pennsylvania Appalachian Trail'),
                                       ('Maryland Appalachian Trail'),
                                       ('Delaware Mason-Dixon Trail'),
                                       ('West Virginia Appalachian Trail'),
                                       ('Virginia Appalachian Trail'),
                                       ('North Carolina Appalachian Trail'),
                                       ('South Carolina Foothills Trail'),
                                       ('Georgia Appalachian Trail'),
                                       ('Florida Florida Trail'),
                                       ('Ohio Buckeye Trail'),
                                       ('Michigan North Country Trail'),
                                       ('Wisconsin Ice Age National Scenic Trail'),
                                       ('Minnesota Superior Hiking Trail'),
                                       ('Iowa Great Western Trail'),
                                       ('Missouri Ozark Trail'),
                                       ('Arkansas Ouachita National Recreation Trail'),
                                       ('Louisiana Kisatchie National Forest Trail'),
                                       ('Mississippi Natchez Trace Parkway Trail'),
                                       ('Alabama Pinhoti National Recreation Trail'),
                                       ('Kentucky Sheltowee Trace Trail'),
                                       ('Tennessee Appalachian Trail');

INSERT INTO trail_imaginary (name) VALUES
                                       ('Texas Lone Star Hiking Trail'),
                                       ('Oklahoma Ouachita National Recreation Trail'),
                                       ('Kansas Flint Hills Trail'),
                                       ('Nebraska Cowboy Recreation and Nature Trail'),
                                       ('South Dakota Centennial Trail'),
                                       ('North Dakota Maah Daah Hey Trail'),
                                       ('Montana Continental Divide Trail'),
                                       ('Wyoming Teton Crest Trail'),
                                       ('Colorado Colorado Trail'),
                                       ('New Mexico Continental Divide Trail'),
                                       ('Arizona Grand Canyon Rim-to-Rim Trail'),
                                       ('Utah Zion Narrows Trail'),
                                       ('Idaho Idaho Centennial Trail'),
                                       ('Washington Pacific Crest Trail'),
                                       ('Oregon Pacific Crest Trail'),
                                       ('California John Muir Trail'),
                                       ('Nevada Tahoe Rim Trail'),
                                       ('Hawaii Kalalau Trail'),
                                       ('Alaska Chilkoot Trail'),
                                       ('Canada West Coast Trail');
CREATE TABLE trail_imaginary_index AS
SELECT * FROM trail_imaginary;
CREATE INDEX index_trail
    ON trail_imaginary_index (id, name);
SELECT * FROM trail_imaginary
WHERE name = 'Mystic Trail';

SELECT * FROM trail_imaginary_index
WHERE name = 'Mystic Trail'
