/*INSERT INTO difficulty (name, description) VALUES
                ('Easy', 'Suitable for beginners and casual participants.'),
                ('Intermediate', 'Requires some skill and experience.'),
                ('Advanced', 'Challenging and suitable for experienced individuals.'),
                ('Expert', 'Very difficult, recommended for highly skilled participants.'),
                ('Extreme', 'Extremely challenging, only for experts and professionals.');

INSERT INTO location (name, country, region, latitude, longitude) VALUES
    ('Rocky Mountain National Park', 'United States', 'Rocky Mountains', 39.5501, -106.0674),
    ('Whistler Blackcomb', 'Canada', 'British Columbia', 53.7267, -127.6476),
    ('Milford Sound', 'New Zealand', 'South Island', -44.7036, 169.1326),
    ('Grand Canyon National Park', 'United States', 'Grand Canyon', 36.107, -112.113),
    ('Sydney Opera House', 'Australia', 'New South Wales', -31.9505, 115.8605),
    ('Munnar', 'India', 'Western Ghats', 10.8505, 76.2711),
    ('French Riviera', 'France', 'Provence-Alpes-Côte dAzur', 43.9426, 6.6501),
    ('Burj Khalifa', 'United Arab Emirates', 'Dubai', 25.2769, 55.2963),
    ('Sognefjord', 'Norway', 'Vestland', 60.472, 8.4689),
    ('Table Mountain', 'South Africa', 'Western Cape', -33.9249, 18.4241),
    ('Iguazu Falls', 'Argentina', 'Misiones', -26.1921, -54.6564),
    ('Phuket Island', 'Thailand', 'Phuket', 7.8804, 98.3923);
INSERT INTO location (name, country, region, latitude, longitude) VALUES
('Mountain View', 'United States', 'California', 37.3861, -122.0839),
('Golden Gate Bridge', 'United States', 'California', 37.8199, -122.4783),
('Grand Canyon', 'United States', 'Arizona', 36.1069, -112.1129),
('Niagara Falls', 'United States', 'New York', 43.0812, -79.0742),
('Yellowstone National Park', 'United States', 'Wyoming', 44.4279, -110.5885),
('Great Barrier Reef', 'Australia', 'Queensland', -18.2871, 147.6992),
('Mount Everest', 'Nepal', 'Himalayas', 27.9881, 86.9250),
('Machu Picchu', 'Peru', 'Cusco', -13.1631, -72.5450),
('Serengeti National Park', 'Tanzania', 'Arusha', -2.1540, 34.6857),
('Antelope Canyon', 'United States', 'Arizona', 36.8619, -111.3743),
('Taj Mahal', 'India', 'Uttar Pradesh', 27.1751, 78.0421),
('Bora Bora', 'French Polynesia', 'Society Islands', -16.5004, -151.7415),
('Eiffel Tower', 'France', 'Île-de-France', 48.8584, 2.2945),
('Victoria Falls', 'Zambia', 'Southern', -17.9244, 25.8567),
('Matterhorn', 'Switzerland', 'Valais', 45.9767, 7.6581),
('Great Wall of China', 'China', 'Beijing', 40.4319, 116.5704),
('Sydney Opera House', 'Australia', 'New South Wales', -33.8568, 151.2153),
('Petra', 'Jordan', 'Ma\'an', 30.3285, 35.4444),
('Santorini', 'Greece', 'South Aegean', 36.3932, 25.4615),
('Galápagos Islands', 'Ecuador', 'Galápagos', -0.8326, -91.1347);  
 */
/*INSERT INTO trail (name, length, elevation, description, image, location_id) VALUES
                                                                                 ('Majestic Peaks', 10.2, 1800, 'Explore the majestic peaks and breathtaking landscapes.', 'https://cdn.trailhub.com/majestic-peaks-cover.jpg', 1),
                                                                                 ('Sunset Serenade', 6.8, 1080, 'Enjoy a serenade of colors during a mesmerizing sunset trail.', 'https://cdn.trailhub.com/sunset-serenade-cover.jpg', 2),
                                                                                 ('Hidden Waterfalls', 8.5, 1200, 'Discover hidden waterfalls along this enchanting and refreshing trail.', 'https://cdn.trailhub.com/hidden-waterfalls-cover.jpg', 3),
                                                                                 ('Moonlit Escapade', 7.1, 1000, 'Embark on an escapade under the moonlight on this mystical trail.', 'https://cdn.trailhub.com/moonlit-escapade-cover.jpg', 4),
                                                                                 ('Wildflower Wonderland', 5.5, 700, 'Immerse yourself in a wonderland of vibrant wildflowers.', 'https://cdn.trailhub.com/wildflower-wonderland-cover.jpg', 5),
                                                                                 ('Alpine Adventure', 9.8, 2160, 'Embark on an adventure through the breathtaking alpine landscapes.', 'https://cdn.trailhub.com/alpine-adventure-cover.jpg', 6),
                                                                                 ('Mystic Lakes', 7.6, 1700, 'Explore the mystical lakes surrounded by scenic beauty.', 'https://cdn.trailhub.com/mystic-lakes-cover.jpg', 7),
                                                                                 ('Golden Meadows', 11.45, 1100, 'Hike through golden meadows and enjoy the beauty of nature.', 'https://cdn.trailhub.com/golden-meadows-cover.jpg', 8),
                                                                                 ('Eagle''s Peak', 10.8, 2000, 'Reach the majestic Eagle''s Peak for panoramic views of the landscape.', 'https://cdn.trailhub.com/eagles-peak-cover.jpg', 9),
                                                                                 ('Sunrise Serenity', 7, 800, 'Experience the serenity of nature with a beautiful sunrise hike.', 'https://cdn.trailhub.com/sunrise-serenity-cover.jpg', 10),
                                                                                 ('Whispering Pines', 9.5, 1300, 'Wander through a trail surrounded by the soothing sounds of whispering pines.', 'https://cdn.trailhub.com/whispering-pines-cover.jpg', 11),
                                                                                 ('Frosty Peaks', 11.2, 1800, 'Embark on a winter adventure with frost-covered peaks and stunning vistas.', 'https://cdn.trailhub.com/frosty-peaks-cover.jpg', 12),
                                                                                 ('Crystal Cascades', 6.7, 900, 'Discover the beauty of crystal-clear cascades along this refreshing trail.', 'https://cdn.trailhub.com/crystal-cascades-cover.jpg', 13),
                                                                                 ('Hidden Valleys', 14.1, 2500, 'Explore the hidden valleys and experience the diversity of landscapes.', 'https://cdn.trailhub.com/hidden-valleys-cover.jpg', 14),
                                                                                 ('Pine Ridge Trail', 8.9, 1200, 'Hike through the scenic Pine Ridge Trail with breathtaking pine forest views.', 'https://cdn.trailhub.com/pine-ridge-trail-cover.jpg', 15),
                                                                                 ('Mountain Majesty', 9.3, 1600, 'Experience the majesty of the mountains on this challenging trail.', 'https://cdn.trailhub.com/mountain-majesty-cover.jpg', 16),
                                                                                 ('Sunrise Summit', 5.7, 1000, 'Catch the first rays of sunrise from the summit of this picturesque trail.', 'https://cdn.trailhub.com/sunrise-summit-cover.jpg', 17),
                                                                                 ('Autumn Splendor Trail', 7.4, 1200, 'Enjoy the splendor of autumn colors on this scenic trail.', 'https://cdn.trailhub.com/autumn-splendor-cover.jpg', 18),
                                                                                 ('Misty Meadows', 6.1, 800, 'Explore misty meadows and discover hidden wonders.', 'https://cdn.trailhub.com/misty-meadows-cover.jpg', 19),
                                                                                 ('Riverfront Trail', 10.5, 1400, 'Follow the river on this trail offering beautiful riverfront views.', 'https://cdn.trailhub.com/riverfront-trail-cover.jpg', 20),
                                                                                 ('Tranquil Valley Trail', 8.2, 1100, 'Discover tranquility in the serene valley along this peaceful trail.', 'https://cdn.trailhub.com/tranquil-valley-cover.jpg', 21),
                                                                                 ('Echoing Canyon', 6.9, 900, 'Hike through echoing canyons and listen to the sounds bounce off the walls.', 'https://cdn.trailhub.com/echoing-canyon-cover.jpg', 22),
                                                                                 ('Forest Glade Trail', 5.3, 700, 'Stroll through a serene forest glade filled with natural beauty.', 'https://cdn.trailhub.com/forest-glade-cover.jpg', 23),
                                                                                 ('Vibrant Vista Trail', 7.8, 1300, 'Enjoy vibrant vistas and panoramic views on this breathtaking trail.', 'https://cdn.trailhub.com/vibrant-vista-cover.jpg', 24),
                                                                                 ('Sunny Summit Trail', 8.6, 1500, 'Reach the sunny summit and be rewarded with stunning views.', 'https://cdn.trailhub.com/sunny-summit-cover.jpg', 25),
                                                                                 ('Rocky Ridge Trail', 6.4, 1000, 'Hike along rocky ridges and admire rugged landscapes.', 'https://cdn.trailhub.com/rocky-ridge-cover.jpg', 26),
                                                                                 ('Secret Springs Trail', 9.7, 1700, 'Discover secret springs hidden along this scenic trail.', 'https://cdn.trailhub.com/secret-springs-cover.jpg', 27),
                                                                                 ('Golden Glades', 7.1, 1200, 'Walk through golden glades and bask in the beauty of nature.', 'https://cdn.trailhub.com/golden-glades-cover.jpg', 28),
                                                                                 ('Majestic Outlook Trail', 8.9, 1600, 'Enjoy majestic outlooks and breathtaking vistas along this trail.', 'https://cdn.trailhub.com/majestic-outlook-cover.jpg', 29),
                                                                                 ('Whispering Winds', 6.5, 1000, 'Feel the whispering winds as you hike through this tranquil trail.', 'https://cdn.trailhub.com/whispering-winds-cover.jpg', 30),
                                                                                 ('Pinnacle Peak', 7.3, 1300, 'Conquer the pinnacle peak and enjoy panoramic views from the top.', 'https://cdn.trailhub.com/pinnacle-peak-cover.jpg', 31),
                                                                                 ('Enchanted Falls Trail', 8.4, 1400, 'Discover the enchantment of cascading falls along this magical trail.', 'https://cdn.trailhub.com/enchanted-falls-cover.jpg', 32),
                                                                                 ('Sapphire Summit Trail', 9.1, 1500, 'Reach the summit of Sapphire Mountain and admire sapphire skies.', 'https://cdn.trailhub.com/sapphire-summit-cover.jpg', 1),
                                                                                 ('Twilight Trail', 6.8, 1100, 'Experience the magic of twilight hues on this mesmerizing trail.', 'https://cdn.trailhub.com/twilight-trail-cover.jpg', 2),
                                                                                 ('Emerald Valley Trail', 7.5, 1200, 'Explore the lush greenery of the emerald valley on this scenic trail.', 'https://cdn.trailhub.com/emerald-valley-cover.jpg', 3);


INSERT INTO trail_rating (trail_id, user_id, score, difficulty_id) VALUES
    (1, 1, 4.5, 1),
    (1, 2, 3.8, 2),
    (1, 3, 1, 3),
    (1, 4, 4, 4),
    (2, 5, 4.7, 5),
    (2, 6, 3.5, 1),
    (2, 7, 4.1, 2),
    (2, 8, 1, 3),
    (3, 9, 4.4, 4),
    (3, 10, 1, 5),
    (3, 11, 4.2, 1),
    (3, 12, 3.6, 2),
    (4, 13, 4, 3),
    (4, 14, 0, 4),
    (4, 15, 4.9, 5),
    (5, 1, 3.8, 1),
    (5, 2, 5, 2),
    (5, 3, 4.1, 3),
    (5, 4, 4.7, 4),
    (6, 5, 4.6, 5),
    (6, 6, 4.4, 1),
    (6, 7, 3.9, 2),
    (6, 8, 3, 3),
    (7, 9, 2, 4),
    (7, 10, 2, 5),
    (7, 11, 3.7, 1),
    (7, 12, 4, 2),
    (8, 13, 3.5, 3),
    (8, 14, 4.1, 4),
    (8, 15, 1, 5),
    (9, 1, 0.8, 1),
    (9, 2, 3.4, 2),
    (9, 3, 4.3, 3),
    (9, 4, 4.6, 4),
    (10, 5, 0, 5),
    (10, 6, 3.9, 1),
    (10, 7, 4.2, 2),
    (10, 8, 3.7, 3),
    (11, 9, 4.5, 4),
    (11, 10, 4, 5),
    (11, 11, 4.1, 1),
    (11, 12, 3.5, 2),
    (12, 13, 4.4, 3),
    (12, 14, 4.8, 4),
    (12, 15, 4.2, 5),
    (13, 1, 3.6, 1),
    (13, 2, 4.3, 2),
    (13, 3, 4.5, 3),
    (13, 4, 4.1, 4),
    (14, 5, 4.4, 5),
    (14, 6, 3.4, 1),
    (14, 7, 4.6, 2),
    (14, 8, 3.6, 3),
    (15, 9, 4.9, 4),
    (15, 10, 3.9, 5),
    (15, 11, 4, 1),
    (15, 12, 3.7, 2),
    (1, 13, 4.5, 3),
    (2, 14, 4.1, 4),
    (3, 15, 4.7, 5),
    (1, 1, 5, 1),
    (1, 16, 4.5, 1),
    (2, 17, 3.8, 2),
    (3, 18, 4.2, 3),
    (4, 19, 4, 4),
    (5, 20, 4.7, 5),
    (6, 21, 3.5, 1),
    (7, 22, 1, 2),
    (8, 23, 3.2, 3),
    (9, 24, 4.8, 4),
    (10, 25, 4.5, 5),
    (11, 26, 3.9, 1),
    (12, 27, 4.1, 2),
    (13, 28, 3.7, 3),
    (14, 29, 4.3, 4),
    (15, 30, 4.6, 5),
    (1, 16, 3.8, 1),
    (2, 17, 4.2, 2),
    (3, 18, 4.5, 3),
    (4, 19, 3.5, 4),
    (5, 20, 4.9, 5),
    (6, 21, 3, 1),
    (7, 22, 4.4, 2),
    (8, 23, 3.8, 3),
    (9, 24, 4.7, 4),
    (10, 25, 4.1, 5),
    (11, 26, 3.6, 1),
    (12, 27, 4.3, 2),
    (13, 28, 3.9, 3),
    (14, 29, 4.5, 4),
    (15, 30, 4.2, 5);
INSERT INTO trail_rating (trail_id, user_id, score, difficulty_id) VALUES
                                                                       (1, 1, 4.5, 1),
                                                                       (2, 2, 4.8, 2),
                                                                       (3, 3, 3.9, 3),
                                                                       (4, 4, 4.2, 4),
                                                                       (5, 5, 4.6, 5),
                                                                       (6, 6, 4.1, 1),
                                                                       (7, 7, 4.9, 2),
                                                                       (8, 8, 3.7, 3),
                                                                       (9, 9, 4.3, 4),
                                                                       (10, 10, 4.7, 5),
                                                                       (11, 11, 4.4, 1),
                                                                       (12, 12, 4.2, 2),
                                                                       (13, 13, 3.8, 3),
                                                                       (14, 14, 4.5, 4),
                                                                       (15, 15, 4.6, 5),
                                                                       (16, 16, 4.3, 1),
                                                                       (17, 17, 4.7, 2),
                                                                       (18, 18, 4.1, 3),
                                                                       (19, 19, 4.4, 4),
                                                                       (20, 20, 4.8, 5),
                                                                       (21, 21, 4.2, 1),
                                                                       (22, 22, 4.6, 2),
                                                                       (23, 23, 4.0, 3),
                                                                       (24, 24, 4.3, 4),
                                                                       (25, 25, 4.9, 5),
                                                                       (26, 26, 4.5, 1),
                                                                       (27, 27, 4.7, 2),
                                                                       (28, 28, 4.2, 3),
                                                                       (29, 29, 4.4, 4),
                                                                       (30, 30, 4.8, 5);
INSERT INTO trail_rating (trail_id, user_id, score, difficulty_id) VALUES
                                                                       (31, 31, 4.6, 1),
                                                                       (32, 32, 4.4, 2),
                                                                       (1, 33, 4.2, 3),
                                                                       (2, 34, 4.8, 4),
                                                                       (3, 35, 4.5, 5),
                                                                       (4, 36, 4.7, 1),
                                                                       (5, 37, 4.3, 2),
                                                                       (6, 38, 4.9, 3),
                                                                       (7, 39, 4.6, 4),
                                                                       (8, 40, 4.1, 5),
                                                                       (9, 41, 4.5, 1),
                                                                       (10, 42, 4.8, 2),
                                                                       (11, 43, 4.4, 3),
                                                                       (12, 44, 4.7, 4),
                                                                       (13, 45, 4.3, 5),
                                                                       (14, 46, 4.6, 1),
                                                                       (15, 47, 4.9, 2),
                                                                       (16, 48, 4.2, 3),
                                                                       (17, 49, 4.5, 4),
                                                                       (18, 50, 4.8, 5),
                                                                       (19, 51, 4.4, 1),
                                                                       (20, 52, 4.7, 2),
                                                                       (21, 53, 4.3, 3),
                                                                       (22, 54, 4.6, 4),
                                                                       (23, 55, 4.9, 5),
                                                                       (24, 56, 4.5, 1),
                                                                       (25, 57, 4.8, 2),
                                                                       (26, 58, 4.2, 3),
                                                                       (27, 59, 4.7, 4),
                                                                       (28, 1, 4.6, 5);
INSERT INTO trail_rating (trail_id, user_id, score, difficulty_id) VALUES
                                                                       (29, 2, 4.9, 1),
                                                                       (30, 3, 4.7, 2),
                                                                       (31, 4, 4.5, 3),
                                                                       (32, 5, 4.8, 4),
                                                                       (27, 6, 4.6, 5),
                                                                       (28, 7, 4.4, 1),
                                                                       (29, 8, 4.7, 2),
                                                                       (30, 9, 4.3, 3),
                                                                       (31, 10, 4.9, 4),
                                                                       (32, 11, 4.5, 5),
                                                                       (27, 12, 4.8, 1),
                                                                       (28, 13, 4.6, 2),
                                                                       (29, 14, 4.4, 3),
                                                                       (30, 15, 4.7, 4),
                                                                       (31, 16, 4.2, 5),
                                                                       (32, 17, 4.9, 1),
                                                                       (27, 18, 4.7, 2),
                                                                       (28, 19, 4.5, 3),
                                                                       (29, 20, 4.8, 4),
                                                                       (30, 21, 4.6, 5),
                                                                       (31, 22, 4.3, 1),
                                                                       (32, 23, 4.7, 2),
                                                                       (27, 24, 4.9, 3),
                                                                       (28, 25, 4.4, 4),
                                                                       (29, 26, 4.8, 5),
                                                                       (30, 27, 4.6, 1),
                                                                       (31, 28, 4.5, 2),
                                                                       (32, 29, 4.2, 3),
                                                                       (27, 30, 4.7, 4),
                                                                       (28, 31, 4.9, 5);
INSERT INTO trail_rating (trail_id, user_id, score, difficulty_id) VALUES
                                                                       (29, 32, 4.6, 1),
                                                                       (30, 33, 4.8, 2),
                                                                       (31, 34, 4.4, 3),
                                                                       (32, 35, 4.7, 4),
                                                                       (27, 36, 4.5, 5),
                                                                       (28, 37, 4.9, 1),
                                                                       (29, 38, 4.3, 2),
                                                                       (30, 39, 4.6, 3),
                                                                       (31, 40, 4.8, 4),
                                                                       (32, 41, 4.2, 5),
                                                                       (27, 42, 4.7, 1),
                                                                       (28, 43, 4.6, 2),
                                                                       (29, 44, 4.5, 3),
                                                                       (30, 45, 4.4, 4),
                                                                       (31, 46, 4.3, 5),
                                                                       (32, 47, 4.9, 1),
                                                                       (27, 48, 4.8, 2),
                                                                       (28, 49, 4.7, 3),
                                                                       (29, 50, 4.6, 4),
                                                                       (30, 51, 4.5, 5),
                                                                       (31, 52, 4.4, 1),
                                                                       (32, 53, 4.3, 2),
                                                                       (27, 54, 4.2, 3),
                                                                       (28, 55, 4.1, 4),
                                                                       (29, 56, 4.0, 5),
                                                                       (30, 57, 4.9, 1),
                                                                       (31, 58, 4.8, 2),
                                                                       (32, 59, 4.7, 3);



  INSERT INTO user (name, email, user_password, type) VALUES
    ('JohnDoe', 'john.doe@example.com', 'Adventure123!', 'regular'),
    ('AliceSmith', 'alice.smith@example.com', 'Hiking@2022', 'pro'),
    ('BobJohnson', 'bob.johnson@example.com', 'TrailRunner87', 'noob'),
    ('EmilyParker', 'emily.parker@example.com', 'ExploreNature', 'regular'),
    ('DavidMiller', 'david.miller@example.com', 'MountainClimb!', 'pro'),
    ('SophiaWilliams', 'sophia.williams@example.com', 'WildflowerLove', 'noob'),
    ('MichaelBrown', 'michael.brown@example.com', 'DesertTrekker', 'regular'),
    ('OliviaJones', 'olivia.jones@example.com', 'CoastalExplorer', 'pro'),
    ('DanielDavis', 'daniel.davis@example.com', 'SunsetChaser', 'noob'),
    ('EmmaWilson', 'emma.wilson@example.com', 'TrailBlazer2022', 'regular'),
    ('LiamThomas', 'liam.thomas@example.com', 'MountainAdventurer', 'pro'),
    ('AvaAnderson', 'ava.anderson@example.com', 'ForestWonder', 'noob'),
    ('JacksonMoore', 'jackson.moore@example.com', 'RiverWalker123', 'regular'),
    ('IsabellaClark', 'isabella.clark@example.com', 'RockyTerrain!', 'pro'),
    ('LucasTaylor', 'lucas.taylor@example.com', 'NatureEnthusiast', 'noob'),
    ('MiaMartin', 'mia.martin@example.com', 'HilltopExplorer', 'regular'),
    ('WilliamWhite', 'william.white@example.com', 'WildlifeWatcher', 'pro'),
    ('AveryHall', 'avery.hall@example.com', 'DesertTrail123', 'noob'),
    ('ScarlettAdams', 'scarlett.adams@example.com', 'CoastalDreamer', 'regular'),
    ('ElijahWard', 'elijah.ward@example.com', 'SunsetAdmirer', 'pro'),
    ('GraceLee', 'grace.lee@example.com', 'TrailSeeker2022', 'noob'),
    ('HenryBarnes', 'henry.barnes@example.com', 'ForestExplorer', 'regular'),
    ('LilyJohnson', 'lily.johnson@example.com', 'RiverBreeze123', 'pro'),
    ('AlexanderSmith', 'alexander.smith@example.com', 'RockyAdventures!', 'noob'),
    ('ChloeHarrison', 'chloe.harrison@example.com', 'MountainTopView', 'regular'),
    ('EthanEvans', 'ethan.evans@example.com', 'HillsideHiker', 'pro'),
    ('AmeliaWood', 'amelia.wood@example.com', 'DesertExplorer', 'noob'),
    ('OwenBaker', 'owen.baker@example.com', 'CoastalJourney', 'regular'),
    ('AriaFisher', 'aria.fisher@example.com', 'SunsetVoyager', 'pro'),
    ('NoahCarter', 'noah.carter@example.com', 'TrailDiscoverer', 'noob');
  INSERT INTO user (name, email, user_password, type) VALUES
                                                        ('SophieBrown', 'sophie.brown@example.com', 'OutdoorLover123', 'regular'),
                                                        ('JackWilson', 'jack.wilson@example.com', 'AdventureTime!', 'pro'),
                                                        ('AvaGarcia', 'ava.garcia@example.com', 'NatureSeeker2022', 'noob'),
                                                        ('LoganMartinez', 'logan.martinez@example.com', 'TrailBlazer87', 'regular'),
                                                        ('GraceYoung', 'grace.young@example.com', 'HikingPassion', 'pro'),
                                                        ('LiamRodriguez', 'liam.rodriguez@example.com', 'MountainExplorer', 'noob'),
                                                        ('ZoeMartinez', 'zoe.martinez@example.com', 'TrailRunner123', 'regular'),
                                                        ('NathanHall', 'nathan.hall@example.com', 'OutdoorAdventurer', 'pro'),
                                                        ('EllaGonzalez', 'ella.gonzalez@example.com', 'NatureLover123!', 'noob'),
                                                        ('CarterPerez', 'carter.perez@example.com', 'AdventureSeeker2022', 'regular'),
                                                        ('ClaireScott', 'claire.scott@example.com', 'HikerLife87', 'pro'),
                                                        ('LukeFlores', 'luke.flores@example.com', 'MountainHiker123', 'noob'),
                                                        ('HannahTorres', 'hannah.torres@example.com', 'TrailBlazer2022!', 'regular'),
                                                        ('IsaacRivera', 'isaac.rivera@example.com', 'AdventureEnthusiast', 'pro'),
                                                        ('MilaCollins', 'mila.collins@example.com', 'NatureExplorer123', 'noob'),
                                                        ('EliPerez', 'eli.perez@example.com', 'MountainClimber87', 'regular'),
                                                        ('AveryWard', 'avery.ward@example.com', 'OutdoorAdventures', 'pro'),
                                                        ('AnnaGutierrez', 'anna.gutierrez@example.com', 'TrailSeeker123!', 'noob'),
                                                        ('JamesNguyen', 'james.nguyen@example.com', 'AdventureTime2022', 'regular'),
                                                        ('EvelynRussell', 'evelyn.russell@example.com', 'HikerExtraordinaire', 'pro'),
                                                        ('MatthewLong', 'matthew.long@example.com', 'NatureLover87', 'noob'),
                                                        ('AddisonKim', 'addison.kim@example.com', 'MountainExplorer123', 'regular'),
                                                        ('HarperNguyen', 'harper.nguyen@example.com', 'AdventureSeeker2022', 'pro'),
                                                        ('SebastianMitchell', 'sebastian.mitchell@example.com', 'OutdoorEnthusiast123', 'noob'),
                                                        ('PenelopeFlores', 'penelope.flores@example.com', 'TrailBlazerLife', 'regular'),
                                                        ('AidenDiaz', 'aiden.diaz@example.com', 'MountainAdventures123', 'pro'),
                                                        ('LunaCampbell', 'luna.campbell@example.com', 'NatureLoverLife!', 'noob'),
                                                        ('BenjaminCarter', 'benjamin.carter@example.com', 'TrailSeekerLife2022', 'regular'),
                                                        ('MasonTorres', 'mason.torres@example.com', 'AdventureJunkie', 'pro');

 */
/*INSERT INTO review (trail_id, user_id, title, content, review_date) VALUES
                                                                                          (1, 1, 'Amazing Mountain Trail', 'Had an incredible experience on this trail. The views from the top were breathtaking!', '2022-01-15'),
                                                                                          (2, 2, 'Beautiful Forest Hike', 'A peaceful hike through the dense forest. Loved every moment of it.', '2022-02-05'),
                                                                                          (2, 3, 'Trail Running Adventure', 'Great trail for running! The varied terrain kept it interesting.', '2022-03-12'),
                                                                                          (4, 4, 'Nature Exploration', 'Explored deep canyons and enjoyed the beauty of the natural surroundings.', '2022-04-20'),
                                                                                          (5, 5, 'Scenic Riverbank Walk', 'Relaxing walk along the riverbank with soothing sounds of nature.', '2022-05-08'),
                                                                                          (6, 6, 'Panoramic Hilltop Vista', 'The short trail led to an amazing panoramic vista. Highly recommend!', '2022-06-17'),
                                                                                          (5, 8, 'Coastal Trail Bliss', 'Enjoyed the coastal views and the refreshing breeze. Perfect for a coastal hike.', '2022-08-04'),
                                                                                          (1, 10, 'Spectacular Sunset Ridge', 'Caught the breathtaking sunset from the ridge. A must-visit spot.', '2022-10-02'),
                                                                                          (1, 11, 'Memorable Mountain Adventure', 'Challenging trail with rewarding views. Definitely worth the effort!', '2022-11-11'),
                                                                                          (2, 12, 'Enchanting Forest Exploration', 'The forest trail was magical, like stepping into a fairy tale.', '2022-12-22'),
                                                                                          (3, 13, 'Canyon Beauty', 'Explored the grandeur of the canyon. A true natural wonder!', '2023-01-08'),
                                                                                          (4, 14, 'Rocky Adventure', 'Navigating through rocky terrains added an exciting element to the trek.', '2023-02-14'),
                                                                                          (5, 15, 'Natures Canvas', 'The trail showcased natures beauty at its finest. A picture-perfect experience.', '2023-03-25'),
                                                                                          (6, 16, 'Hilltop Serenity', 'Hiked to a serene hilltop with breathtaking views. A peaceful escape.', '2023-04-30'),
                                                                                          (6, 17, 'Natures Symphony', 'The sounds of nature accompanied the hike, making it a memorable experience.', '2023-05-19'),
                                                                                          (3, 19, 'Coastal Trail Delight', 'Moderate difficulty with rewarding coastal scenery. Enjoyed every step!', '2023-07-15'),
                                                                                          (1, 21, 'Trailblazing Adventure', 'Challenged myself on this trail, and it was a thrilling adventure.', '2023-09-12'),
                                                                                          (2, 22, 'Forest Wonderland', 'The forest trail felt like stepping into a wonderland. Loved the diversity of flora.', '2023-10-23'),
                                                                                          (3, 23, 'River Breeze Bliss', 'Hiking along the river provided a refreshing experience with cool breezes.', '2023-11-05'),
                                                                                          (4, 24, 'Rocky Escapade', 'Navigating the rocky terrains was a bit challenging but added excitement to the trek.', '2023-12-18'),
                                                                                          (5, 25, 'Mountain Majesty', 'The trail led to majestic mountain views. A must-do for nature enthusiasts!', '2024-01-07'),
                                                                                          (6, 26, 'Hillside Harmony', 'Hiking along the hillsides provided a harmonious experience with nature.', '2024-02-14'),
                                                                                          (2, 2, 'Forest Symphony', 'The sounds of the forest created a symphony during the hike. Natures music at its best.', '2024-08-05'),
                                                                                          (3, 3, 'Canyon Colors', 'The vibrant colors of the canyon walls were a visual feast. A captivating trek.', '2024-09-18'),
                                                                                          (4, 4, 'Rocky Challenge', 'Conquered the rocky challenge of the trail. A test of endurance and determination.', '2024-10-03'),
                                                                                          (5, 5, 'Riverbank Retreat', 'Relaxed by the riverbank, taking in the serenity of the surroundings. A peaceful escape.', '2024-11-14'),
                                                                                          (6, 6, 'Hilltop Haven', 'Found a serene haven at the hilltop, away from the hustle and bustle. A hidden gem.', '2024-12-26'),
                                                                                          (4, 7, 'Wildflower Wonderland', 'The trail transformed into a colorful wonderland with blooming wildflowers. Enchanting.', '2025-01-08'),
                                                                                          (4, 9, 'Coastal Tranquility', 'Experienced the tranquility of the coast with calming waves and scenic coastal views.', '2025-03-05'),
                                                                                          (3, 1, 'Mountain Majesty Redux', 'Returned to the majestic mountain trail for another dose of awe-inspiring views.', '2025-05-01'),
                                                                                          (3, 2, 'Forest Exploration II', 'Continued the exploration of the enchanting forest, uncovering new hidden spots.', '2025-06-14'),
                                                                                          (3, 3, 'River Adventure', 'Navigated the river trail, experiencing the adventure and beauty along the flowing waters.', '2025-07-27'),
                                                                                          (3, 4, 'Rocky Revelations', 'The rocky terrains revealed unique geological formations, making the trek a geological adventure.', '2025-08-10'),
                                                                                          (5, 5, 'Mountain Vista Delight', 'Enjoyed a delightful hike to another mountain vista, showcasing the diversity of the landscape.', '2025-09-23'),
                                                                                          (1, 1, 'Amazing Experience!', 'The views from the top were absolutely breathtaking. A must-do trail!', '2022-01-16'),
                                                                                          (1, 2, 'Unforgettable Hike', 'Challenging but rewarding. The summit provides a sense of accomplishment.', '2022-02-02'),
                                                                                          (1, 3, 'Spectacular Scenery', 'Nature at its best! The trail offers panoramic views that leave you in awe.', '2022-02-20'),
                                                                                          (2, 4, 'Enchanting Forest Trail', 'Like walking through a fairy tale. The dense forest adds a magical touch to the hike.', '2022-03-10'),
                                                                                          (2, 5, 'Peaceful Retreat', 'A serene and peaceful hike. Perfect for those looking to escape into nature.', '2022-03-28'),
                                                                                          (2, 6, 'Trail Runner''s Delight', 'Great for running with varied terrain. Keeps the adventure alive!', '2022-04-15'),
                                                                                          (3, 7, 'Grand Canyon Exploration', 'Explored the grandeur of the canyon. A natural wonder worth experiencing.', '2022-05-01'),
                                                                                          (3, 8, 'Canyon Colors', 'Vibrant colors of the canyon walls create a visual feast. A photographer''s dream!', '2022-05-18'),
                                                                                          (3, 9, 'Canyon Beauty', 'The trail offers a unique adventure along the flowing waters of the canyon.', '2022-06-02'),
                                                                                          (4, 10, 'Rocky Terrain Challenge', 'Conquered the challenging rocky terrains. A test of endurance and determination.', '2022-06-20'),
                                                                                          (4, 11, 'Nature Exploration', 'Immersed in the beauty of natural surroundings. The deep canyons add an extra thrill.', '2022-07-07'),
                                                                                          (4, 12, 'Rocky Adventure', 'Navigating through the rocky terrains added an exciting element to the trek.', '2022-07-23'),
                                                                                          (5, 13, 'Riverbank Bliss', 'A relaxing walk along the riverbank with soothing sounds of nature. Truly refreshing!', '2022-08-10'),
                                                                                          (5, 14, 'Scenic Beauty', 'The trail showcases nature''s beauty at its finest. Every step is a picture-perfect experience.', '2022-08-26'),
                                                                                          (5, 15, 'Coastal Trail Retreat', 'Perfect for a coastal escape. The coastal views and breeze make it a delightful hike.', '2022-09-12'),
                                                                                          (6, 16, 'Hilltop Views', 'Hiked to a serene hilltop with breathtaking views. A peaceful escape from the hustle.', '2022-09-28'),
                                                                                          (6, 17, 'Symphony of Nature', 'The sounds of nature accompanied the hike, making it a memorable and harmonious experience.', '2022-10-15'),
                                                                                          (6, 18, 'Hidden Gem', 'Found a serene haven at the hilltop, away from the bustle. A true hidden gem!', '2022-10-31'),
                                                                                          (7, 1, 'Enchanting Wildflowers', 'The trail was lined with colorful wildflowers. Absolutely enchanting.', '2023-07-23'),
                                                                                          (8, 2, 'Coastal Trail Bliss', 'Enjoyed the coastal views and the refreshing breeze. Perfect for a coastal hike.', '2023-08-04'),
                                                                                          (9, 3, 'Moderate Difficulty', 'Moderate difficulty with stunning coastal views. Loved the ocean breeze!', '2023-09-15'),
                                                                                          (10, 4, 'Breathtaking Sunset Ridge', 'Caught the breathtaking sunset from the ridge. A must-visit spot.', '2023-10-02'),
                                                                                          (11, 5, 'Memorable Mountain Adventure', 'Challenging trail with rewarding views. Definitely worth the effort!', '2023-11-11'),
                                                                                          (12, 6, 'Enchanting Forest Exploration', 'The forest trail was magical, like stepping into a fairy tale.', '2023-12-22'),
                                                                                          (13, 7, 'Canyon Beauty', 'Explored the grandeur of the canyon. A true natural wonder!', '2024-01-08'),
                                                                                          (14, 8, 'Rocky Adventure', 'Navigating through rocky terrains added an exciting element to the trek.', '2024-02-14'),
                                                                                          (15, 9, 'Nature''s Canvas', 'The trail showcased nature''s beauty at its finest. A picture-perfect experience.', '2024-03-25'),
                                                                                          (7, 10, 'Wildflower Wonderland', 'The trail transformed into a colorful wonderland with blooming wildflowers. Enchanting.', '2025-01-08'),
                                                                                          (8, 11, 'Desert Serenity', 'Discovered the tranquil side of the desert landscape. A serene desert trekking experience.', '2025-02-21'),
                                                                                          (9, 12, 'Coastal Tranquility', 'Experienced the tranquility of the coast with calming waves and scenic coastal views.', '2025-03-05'),
                                                                                          (10, 13, 'Sunset Seeker', 'Embarked on a journey to seek the perfect sunset view. Nature''s canvas painted with hues of warmth.', '2025-04-18'),
                                                                                          (11, 14, 'Mountain Majesty Redux', 'Returned to the majestic mountain trail for another dose of awe-inspiring views.', '2025-05-01'),
                                                                                          (12, 15, 'Forest Exploration II', 'Continued the exploration of the enchanting forest, uncovering new hidden spots.', '2025-06-14'),
                                                                                          (13, 16, 'River Adventure', 'Navigated the river trail, experiencing the adventure and beauty along the flowing waters.', '2025-07-27'),
                                                                                          (14, 17, 'Rocky Revelations', 'The rocky terrains revealed unique geological formations, making the trek a geological adventure.', '2025-08-10'),
                                                                                          (15, 18, 'Mountain Vista Delight', 'Enjoyed a delightful hike to another mountain vista, showcasing the diversity of the landscape.', '2025-09-23'),
                                                                                          (7, 19, 'Trail Serenity', 'Found serenity along the trail. A peaceful escape from the routine.', '2025-10-05'),
                                                                                          (8, 20, 'Coastal Harmony', 'The coastal trail provided a harmonious experience with nature. Refreshing!', '2025-11-18'),
                                                                                          (9, 21, 'Sunset Exploration', 'Explored the trail during the mesmerizing hues of sunset. Spectacular views!', '2025-12-01'),
                                                                                          (10, 22, 'Forest Oasis', 'Discovered an oasis within the forest trail. Nature''s hidden gem!', '2026-01-14'),
                                                                                          (11, 23, 'Canyon Tranquility', 'Enjoyed a tranquil experience in the heart of the canyon. Serene surroundings.', '2026-02-27'),
                                                                                          (12, 24, 'Rocky Challenge II', 'Took on the challenge of rocky terrains again. Pushing limits!', '2026-03-12'),
                                                                                          (13, 25, 'Riverbank Reflections', 'Moments of reflection by the riverbank. Perfect for introspection.', '2026-04-25'),
                                                                                          (14, 26, 'Mountain Ascent', 'Embarked on an ascent to the mountain summit. Breathtaking views at the top!', '2026-05-08'),
                                                                                          (1, 26, 'Great Hike!', 'Enjoyed the trail a lot.', '2024-03-06'),
                                                                                          (2, 27, 'Beautiful Scenery', 'Breathtaking views!', '2024-03-07'),
                                                                                          (3, 28, 'Challenging but Fun', 'The trail had some difficult sections, but it was worth it.', '2024-03-08'),
                                                                                          (4, 29, 'Peaceful Retreat', 'Found serenity in nature.', '2024-03-09'),
                                                                                          (5, 30, 'Family Adventure', 'Took the kids and had a wonderful time.', '2024-03-10'),
                                                                                          (1, 1, 'Great Trail!', 'This trail was amazing!', '2024-03-06'),
                                                                                          (2, 2, 'Awesome Hike', 'I loved the scenery on this trail.', '2024-03-07'),
                                                                                          (3, 3, 'Trail Adventure', 'Had a great time exploring this trail.', '2024-03-08'),
                                                                                          (4, 4, 'Beautiful Nature', 'The nature on this trail is stunning.', '2024-03-09'),
                                                                                          (5, 5, 'Scenic Route', 'The route offered breathtaking views.', '2024-03-10'),
                                                                                          (6, 6, 'Nature Walk', 'A peaceful walk through nature.', '2024-03-11'),
                                                                                          (7, 7, 'Mountain Trail', 'Hiking this mountain trail was challenging but rewarding.', '2024-03-12'),
                                                                                          (8, 8, 'Trailblazing', 'Blazing new trails and loving it!', '2024-03-13'),
                                                                                          (9, 9, 'Sunset Hike', 'Witnessed a beautiful sunset on this trail.', '2024-03-14'),
                                                                                          (10, 10, 'Trail Tales', 'Sharing stories with fellow hikers.', '2024-03-15'),
                                                                                          (11, 11, 'Hilltop Views', 'Reached the hilltop for panoramic views.', '2024-03-16'),
                                                                                          (12, 12, 'Nature''s Symphony', 'Listened to the symphony of nature throughout the trail.', '2024-03-17'),
                                                                                          (13, 13, 'River Walk', 'Enjoyed a calming walk along the river.', '2024-03-18'),
                                                                                          (14, 14, 'Trail Reflections', 'Reflecting on life while hiking this trail.', '2024-03-19'),
                                                                                          (15, 15, 'Trailblazers Unite', 'Uniting with fellow trailblazers!', '2024-03-20'),
                                                                                          (1, 16, 'Morning Hike', 'Started the day with an invigorating hike.', '2024-03-21'),
                                                                                          (2, 17, 'Forest Exploration', 'Explored the depths of the forest on this trail.', '2024-03-22'),
                                                                                          (3, 18, 'Peak Challenge', 'Challenged myself to reach the peak.', '2024-03-23'),
                                                                                          (4, 19, 'Trail Serenity', 'Found serenity in the midst of nature.', '2024-03-24'),
                                                                                          (5, 20, 'Trailblazing Solo', 'Solo trailblazing adventure!', '2024-03-25'),
                                                                                          (6, 21, 'Wildlife Encounter', 'Encountered amazing wildlife along the trail.', '2024-03-26'),
                                                                                          (7, 22, 'Rocky Terrain', 'Navigated through challenging rocky terrain.', '2024-03-27'),
                                                                                          (8, 23, 'Trail Photography', 'Captured stunning moments on camera.', '2024-03-28'),
                                                                                          (9, 24, 'Sunrise Hike', 'Chased the sunrise on this early morning hike.', '2024-03-29'),
                                                                                          (10, 25, 'Trail Meditations', 'Meditated in the peacefulness of the trail.', '2024-03-30'),
                                                                                          (11, 26, 'Countryside Stroll', 'A leisurely stroll through the countryside.', '2024-03-31'),
                                                                                          (12, 27, 'Trailside Picnic', 'Enjoyed a picnic with a view.', '2024-04-01'),
                                                                                          (13, 28, 'Trail Runner', 'Running the trail for an adrenaline rush.', '2024-04-02'),
                                                                                          (14, 29, 'Trailside Sketching', 'Captured the beauty of nature through sketching.', '2024-04-03'),
                                                                                          (15, 30, 'Trail Companions', 'Hiking with beloved companions.', '2024-04-04');
INSERT INTO review (trail_id, user_id, title, content, review_date) VALUES
(1, 1, 'Fantastic Trail!', 'The views were absolutely stunning. A must-do trail for any nature lover.', '2024-04-05'),
(2, 2, 'Trailblazing Adventure', 'Challenging but exhilarating. Loved every moment of it!', '2024-04-06'),
(3, 3, 'Spectacular Scenery', 'Nature at its finest. The beauty of this trail is truly breathtaking.', '2024-04-07'),
(4, 4, 'Rocky Adventure', 'Navigating through the rocky terrains was both thrilling and rewarding.', '2024-04-08'),
(5, 5, 'Riverbank Retreat', 'Relaxed by the riverbank, listening to the gentle flow of water. A peaceful escape.', '2024-04-09'),
(6, 6, 'Hilltop Haven', 'Found tranquility at the hilltop, away from the chaos of daily life. A hidden gem indeed.', '2024-04-10'),
(7, 7, 'Wildflower Wonderland', 'The trail was alive with vibrant colors of wildflowers. Nature\'s masterpiece!', '2024-04-11'),
(8, 8, 'Coastal Bliss', 'The coastal views were breathtaking, and the salty breeze was invigorating.', '2024-04-12'),
(9, 9, 'Mountain Majesty', 'Reached the summit and felt like I was on top of the world. Majestic views all around.', '2024-04-13'),
(10, 10, 'Forest Exploration', 'The forest trail was enchanting, with towering trees and hidden surprises at every turn.', '2024-04-14'),
(11, 11, 'Canyon Adventure', 'Explored the depths of the canyon, feeling small amidst its grandeur. An unforgettable experience.', '2024-04-15'),
(12, 12, 'Sunset Serenity', 'Witnessed a breathtaking sunset from the trail, painting the sky in hues of orange and pink.', '2024-04-16'),
(13, 13, 'Trail Tranquility', 'Found peace and solitude on this trail, away from the hustle and bustle of city life.', '2024-04-17'),
(14, 14, 'Panoramic Views', 'The panoramic views from the trail were simply awe-inspiring. Mother Nature\'s masterpiece!', '2024-04-18'),
(15, 15, 'Trailblazing Solo', 'Embarked on a solo adventure and discovered the true beauty of solitude in nature.', '2024-04-19'),
(1, 2, 'Mesmerizing Views', 'The views from the trail were like something out of a dream. Absolutely mesmerizing!', '2024-04-20'),
(2, 3, 'Trail Runner''s Paradise', 'Perfect trail for running, with challenging terrain and breathtaking scenery.', '2024-04-21'),
(3, 4, 'Nature''s Symphony', 'Listened to the symphony of birds and rustling leaves as I hiked. Nature\'s music at its best.', '2024-04-22'),
(4, 5, 'Rocky Challenge II', 'Took on the challenge of rocky terrains again and emerged victorious. A true test of endurance.', '2024-04-23'),
(5, 6, 'Riverbank Reflections', 'Spent moments of quiet reflection by the riverbank, feeling at peace with myself and nature.', '2024-04-24'),
(6, 7, 'Mountain Ascent', 'Reached new heights as I ascended the mountain trail. The views from the top were breathtaking.', '2024-04-25'),
(7, 8, 'Forest Escape', 'Escaped into the depths of the forest, feeling a deep connection with nature.', '2024-04-26'),
(8, 9, 'Coastal Charm', 'Charmed by the beauty of the coastal trail, with its rugged cliffs and crashing waves.', '2024-04-27'),
(9, 10, 'Hilltop Hike', 'Hiked to the hilltop and felt like I was on top of the world. A truly exhilarating experience.', '2024-04-28'),
(10, 11, 'Canyon Wonder', 'Wondered at the sheer magnificence of the canyon, carved by the forces of nature over millennia.', '2024-04-29'),
(11, 12, 'Sunset Splendor', 'Experienced the splendor of a sunset from the trail, with the sky ablaze in fiery colors.', '2024-04-30'),
(12, 13, 'Trail Meditation', 'Meditated amidst the tranquility of nature, feeling a sense of calm wash over me.', '2024-05-01'),
(13, 14, 'Wildlife Encounter', 'Encountered a variety of wildlife along the trail, from deer to birds to small mammals.', '2024-05-02'),
(14, 15, 'Mountain Majesty', 'Once again, the majestic views from the mountain trail left me in awe of the natural world.', '2024-05-03'),
(15, 1, 'Forest Fantasy', 'The forest trail felt like stepping into a fantasy world, with its towering trees and lush undergrowth.', '2024-05-04');
INSERT INTO review (trail_id, user_id, title, content, review_date) VALUES
(1, 3, 'Amazing Adventure', 'Had an amazing adventure on this trail. The views were absolutely breathtaking!', '2024-05-05'),
(2, 4, 'Enchanted Forest', 'Felt like I was walking through an enchanted forest. The atmosphere was magical.', '2024-05-06'),
(3, 5, 'Canyon Marvel', 'Marvelled at the beauty and grandeur of the canyon. Nature\'s masterpiece!', '2024-05-07'),
(4, 6, 'Rocky Journey', 'The rocky journey was challenging but immensely rewarding. A true test of perseverance.', '2024-05-08'),
(5, 7, 'Riverbank Oasis', 'Found a peaceful oasis by the riverbank. Nature\'s tranquility at its best.', '2024-05-09'),
(6, 8, 'Hilltop Retreat', 'Retreated to the hilltop for a moment of serenity and reflection. A perfect escape.', '2024-05-10'),
(7, 9, 'Wildflower Wonderland', 'The trail was alive with colorful wildflowers, creating a truly magical experience.', '2024-05-11'),
(8, 10, 'Coastal Beauty', 'The coastal beauty was awe-inspiring, with stunning vistas at every turn.', '2024-05-12'),
(9, 11, 'Mountain Majesty', 'Witnessed the majesty of the mountains from the summit. A breathtaking experience.', '2024-05-13'),
(10, 12, 'Enchanted Forest', 'Explored the depths of the enchanted forest, discovering hidden wonders along the way.', '2024-05-14'),
(11, 13, 'Canyon Wonders', 'Wondered at the wonders of the canyon, shaped by the forces of nature over eons.', '2024-05-15'),
(12, 14, 'Sunset Bliss', 'Experienced pure bliss watching the sunset from the trail. Nature\'s beauty at its finest.', '2024-05-16'),
(13, 15, 'Tranquil Trail', 'Found tranquility on the trail, far away from the hustle and bustle of city life.', '2024-05-17'),
(14, 1, 'Panoramic Paradise', 'The panoramic views from the trail were nothing short of paradise. A truly heavenly experience.', '2024-05-18'),
(15, 2, 'Solo Sojourn', 'Embarked on a solo sojourn and discovered the true joy of solitude in nature.', '2024-05-19'),
(1, 4, 'Spectacular Scenery', 'The scenery along the trail was simply spectacular. A feast for the eyes!', '2024-05-20'),
(2, 5, 'Trailblazing Fun', 'Had a lot of fun trailblazing through this beautiful landscape. An adventure to remember!', '2024-05-21'),
(3, 6, 'Canyon Exploration', 'Explored the depths of the canyon, uncovering hidden treasures along the way.', '2024-05-22'),
(4, 7, 'Rocky Challenge', 'Took on the rocky challenge and emerged stronger on the other side. A true triumph!', '2024-05-23'),
(5, 8, 'Riverbank Retreat', 'Retreated to the riverbank for a moment of peace and relaxation. Nature\'s therapy!', '2024-05-24'),
(6, 9, 'Hilltop Haven', 'Found solace and tranquility at the hilltop. A sanctuary away from the chaos of daily life.', '2024-05-25'),
(7, 10, 'Wildflower Wonderland', 'The trail was a wonderland of wildflowers, painting the landscape in vibrant colors.', '2024-05-26'),
(8, 11, 'Coastal Escape', 'Escaped to the coast for a breath of fresh air and stunning coastal views. Pure bliss!', '2024-05-27'),
(9, 12, 'Mountain Magic', 'Experienced the magic of the mountains firsthand. Nature\'s wonders never cease to amaze.', '2024-05-28'),
(10, 13, 'Forest Fantasy', 'The forest trail felt like stepping into a fantasy world, with its ancient trees and mystical aura.', '2024-05-29'),
(11, 14, 'Canyon Majesty', 'Witnessed the majestic beauty of the canyon, carved by the hands of time. A truly humbling experience.', '2024-05-30'),
(12, 15, 'Sunset Serenade', 'Serenaded by the sunset on the trail, with the sky ablaze in hues of orange and pink. Nature\'s symphony!', '2024-05-31'),
(13, 1, 'Trail Tranquility', 'Found peace and tranquility on the trail, with only the sounds of nature to accompany me. Blissful!', '2024-06-01'),
(14, 2, 'Panoramic Views', 'The panoramic views from the trail were breathtaking, stretching as far as the eye could see. Simply awe-inspiring!', '2024-06-02'),
(15, 3, 'Solo Expedition', 'Embarked on a solo expedition and discovered the true beauty of solitude in nature. An unforgettable journey!', '2024-06-03');
```
INSERT INTO review (trail_id, user_id, title, content, review_date) VALUES
                                                                        (1, 1, 'Fantastic Hike', 'I had a fantastic time hiking this trail. The views were breathtaking!', '2023-05-10'),
                                                                        (2, 2, 'Sunset Beauty', 'Witnessing the sunset from this trail was truly a magical experience.', '2023-06-22'),
                                                                        (3, 3, 'Hidden Gem', 'This trail is a hidden gem! The waterfalls were stunning.', '2023-07-15'),
                                                                        (4, 4, 'Mystical Adventure', 'Embarking on this trail under the moonlight felt like a mystical adventure.', '2023-08-03'),
                                                                        (5, 5, 'Wildflower Wonderland', 'The wildflowers along this trail created a mesmerizing wonderland.', '2023-09-18'),
                                                                        (6, 6, 'Alpine Beauty', 'The alpine landscapes on this trail were breathtaking. Highly recommend!', '2023-10-09'),
                                                                        (7, 7, 'Scenic Lakes', 'The lakes along this trail offered serene and scenic views.', '2023-11-27'),
                                                                        (8, 8, 'Golden Meadows', 'Walking through golden meadows was a refreshing experience.', '2023-12-14'),
                                                                        (9, 9, 'Eagle\'s Peak Summit', 'Reaching the summit of Eagle\'s Peak was exhilarating!', '2024-01-05'),
                                                                        (10, 10, 'Serenity at Sunrise', 'Experiencing the serenity of nature during sunrise was unforgettable.', '2024-02-19'),
                                                                        (11, 11, 'Whispering Pines', 'The sound of whispering pines along this trail was so soothing.', '2024-03-08'),
                                                                        (12, 12, 'Winter Adventure', 'This trail offered stunning vistas of frost-covered peaks.', '2024-04-11'),
                                                                        (13, 13, 'Crystal Clear Cascades', 'The cascades along this trail were crystal clear and beautiful.', '2024-05-22'),
                                                                        (14, 14, 'Diverse Landscapes', 'Exploring the hidden valleys on this trail was an adventure.', '2024-06-30'),
                                                                        (15, 15, 'Pine Forest Paradise', 'The pine forest views on this trail were absolutely enchanting.', '2024-07-17'),
                                                                        (16, 16, 'Mountain Majesty', 'The majesty of the mountains on this trail left me in awe.', '2024-08-29'),
                                                                        (17, 17, 'Summit Sunrise', 'Watching the sunrise from the summit of this trail was breathtaking.', '2024-09-14'),
                                                                        (18, 18, 'Autumn Splendor', 'The autumn colors along this trail were simply spectacular.', '2024-10-28'),
                                                                        (19, 19, 'Misty Meadows', 'Walking through misty meadows felt like a dream.', '2024-11-12'),
                                                                        (20, 20, 'Riverfront Beauty', 'The riverfront views along this trail were absolutely stunning.', '2024-12-03'),
                                                                        (21, 21, 'Tranquil Valley', 'The tranquil valley along this trail was a peaceful escape.', '2025-01-20'),
                                                                        (22, 22, 'Echoing Canyons', 'The echoing canyons on this trail created a unique atmosphere.', '2025-02-08'),
                                                                        (23, 23, 'Serenade of Forests', 'Strolling through the forest glade was a serene experience.', '2025-03-15'),
                                                                        (24, 24, 'Vibrant Vistas', 'The vibrant vistas along this trail offered panoramic views.', '2025-04-27'),
                                                                        (25, 25, 'Sunny Summit', 'Reaching the sunny summit was challenging but worth it for the views.', '2025-05-18'),
                                                                        (26, 26, 'Rocky Ridge Adventure', 'Hiking along rocky ridges provided thrilling adventure.', '2025-06-29'),
                                                                        (27, 27, 'Secret Springs Discovery', 'Finding the secret springs along this trail was a delightful surprise.', '2025-07-11'),
                                                                        (28, 28, 'Golden Glades', 'The golden glades on this trail were a sight to behold.', '2025-08-23'),
                                                                        (29, 29, 'Majestic Outlooks', 'The majestic outlooks along this trail offered breathtaking vistas.', '2025-09-07'),
                                                                        (30, 30, 'Whispering Winds', 'Feeling the whispering winds on this trail was a serene experience.', '2025-10-14');
INSERT INTO review (trail_id, user_id, title, content, review_date) VALUES
                                                                        (31, 31, 'Enchanted Forest', 'Walking through this trail felt like stepping into an enchanted forest.', '2025-11-20'),
                                                                        (32, 32, 'Sapphire Summit', 'Reaching the summit of Sapphire Mountain was a challenging but rewarding journey.', '2025-12-12'),
                                                                        (1, 33, 'A Trail to Remember', 'This trail provided unforgettable views and memories.', '2026-01-25'),
                                                                        (2, 34, 'Mesmerizing Sunsets', 'The sunsets from this trail were mesmerizing beyond words.', '2026-02-09'),
                                                                        (3, 35, 'Waterfall Wonderland', 'The waterfalls along this trail created a magical atmosphere.', '2026-03-18'),
                                                                        (4, 36, 'Moonlit Magic', 'Hiking this trail under the moonlight was a magical experience.', '2026-04-05'),
                                                                        (5, 37, 'Wildflower Extravaganza', 'The wildflowers on this trail were a feast for the eyes.', '2026-05-22'),
                                                                        (6, 38, 'Alpine Adventure', 'An adventure through alpine landscapes that left me in awe.', '2026-06-11'),
                                                                        (7, 39, 'Mystical Lakes', 'The mystical lakes along this trail were simply breathtaking.', '2026-07-02'),
                                                                        (8, 40, 'Golden Meadows Delight', 'Walking through golden meadows was pure delight.', '2026-08-14'),
                                                                        (9, 41, 'Eagle''s Peak Panorama', 'The panoramic views from Eagle''s Peak were simply stunning.', '2026-09-27'),
                                                                        (10, 42, 'Sunrise Bliss', 'Experiencing the sunrise from this trail brought a sense of peace.', '2026-10-10'),
                                                                        (11, 43, 'Pine Forest Tranquility', 'The tranquil atmosphere of the pine forest was rejuvenating.', '2026-11-30'),
                                                                        (12, 44, 'Winter Wonderland', 'A winter wonderland with frost-covered peaks and snowy trails.', '2026-12-18'),
                                                                        (13, 45, 'Crystal Cascades Beauty', 'The beauty of the crystal-clear cascades was awe-inspiring.', '2027-01-29'),
                                                                        (14, 46, 'Valley Exploration', 'Exploring the hidden valleys provided endless surprises.', '2027-02-15'),
                                                                        (15, 47, 'Pine Ridge Paradise', 'The pine ridge offered a paradise for nature lovers.', '2027-03-08'),
                                                                        (16, 48, 'Mountain Majesty II', 'Another trail with majestic mountain views that left me speechless.', '2027-04-20'),
                                                                        (17, 49, 'Summit Splendor II', 'The summit views on this trail were equally spectacular.', '2027-05-03'),
                                                                        (18, 50, 'Autumn Aura', 'The autumn aura along this trail was truly enchanting.', '2027-06-14'),
                                                                        (19, 51, 'Misty Meadows II', 'Walking through misty meadows was like entering a dream.', '2027-07-27'),
                                                                        (20, 52, 'Riverfront Reverie', 'The riverfront views provided moments of serene contemplation.', '2027-08-09'),
                                                                        (21, 53, 'Tranquil Valley II', 'The tranquility of the valley offered a much-needed escape.', '2027-09-20'),
                                                                        (22, 54, 'Echoing Canyons II', 'The echoes in the canyons added a sense of mystery to the trail.', '2027-10-05'),
                                                                        (23, 55, 'Forest Glade Serenity', 'The serene atmosphere of the forest glade was rejuvenating.', '2027-11-18'),
                                                                        (24, 56, 'Vibrant Vistas II', 'The vibrant vistas provided endless photo opportunities.', '2027-12-01'),
                                                                        (25, 57, 'Sunny Summit II', 'The sunny summit offered breathtaking views in every direction.', '2028-01-14'),
                                                                        (26, 58, 'Rocky Ridge Revisited', 'Returning to hike the rocky ridges felt like meeting an old friend.', '2028-02-27'),
                                                                        (27, 59, 'Springs Exploration', 'Exploring the secret springs along the trail was an adventure.', '2028-03-10'),
                                                                        (28, 1, 'Golden Glades II', 'The golden glades continued to amaze with their beauty.', '2028-04-20');
INSERT INTO review (trail_id, user_id, title, content, review_date) VALUES
                                                                        (29, 2, 'Majestic Views III', 'The majestic views from this trail never cease to impress.', '2028-05-03'),
                                                                        (30, 3, 'Whispering Winds III', 'The whispering winds added a sense of tranquility to the hike.', '2028-06-15'),
                                                                        (31, 4, 'Enchanted Forest III', 'The forest seemed even more enchanting with each visit.', '2028-07-28'),
                                                                        (32, 5, 'Sapphire Summit III', 'Reaching the summit of Sapphire Mountain was always a thrilling adventure.', '2028-08-10'),
                                                                        (1, 6, 'A Trail to Remember III', 'This trail never fails to leave a lasting impression.', '2028-09-22'),
                                                                        (2, 7, 'Mesmerizing Sunsets III', 'Each sunset from this trail feels like a work of art.', '2028-10-05'),
                                                                        (3, 8, 'Waterfall Wonderland III', 'The waterfalls continue to captivate visitors with their beauty.', '2028-11-17'),
                                                                        (4, 9, 'Moonlit Magic III', 'The moonlit hikes on this trail always feel like stepping into a fairy tale.', '2028-12-30'),
                                                                        (5, 10, 'Wildflower Extravaganza III', 'The wildflowers bloom anew with each passing season.', '2029-01-12'),
                                                                        (6, 11, 'Alpine Adventure III', 'Exploring the alpine landscapes never gets old.', '2029-02-24'),
                                                                        (7, 12, 'Mystical Lakes III', 'The lakes retain their mystical allure no matter how many times you visit.', '2029-03-09'),
                                                                        (8, 13, 'Golden Meadows Delight III', 'Golden meadows offer a timeless beauty that never fades.', '2029-04-21'),
                                                                        (9, 14, 'Eagle''s Peak Panorama III', 'The panoramic views from Eagle''s Peak remain as breathtaking as ever.', '2029-05-04'),
                                                                        (10, 15, 'Sunrise Bliss III', 'Each sunrise brings a new sense of bliss and wonder.', '2029-06-16'),
                                                                        (11, 16, 'Pine Forest Tranquility III', 'The tranquility of the pine forest is a welcome retreat from the chaos of everyday life.', '2029-07-29'),
                                                                        (12, 17, 'Winter Wonderland III', 'The winter wonderland is a magical realm of snow and ice.', '2029-08-11'),
                                                                        (13, 18, 'Crystal Cascades Beauty III', 'The cascades sparkle like diamonds in the sunlight.', '2029-09-23'),
                                                                        (14, 19, 'Valley Exploration III', 'The hidden valleys reveal new wonders with each exploration.', '2029-10-06'),
                                                                        (15, 20, 'Pine Ridge Paradise III', 'The pine ridge offers a paradise for nature lovers seeking solace.', '2029-11-18'),
                                                                        (16, 21, 'Mountain Majesty IV', 'The majesty of the mountains is a humbling sight.', '2029-12-31'),
                                                                        (17, 22, 'Summit Splendor IV', 'The summit offers a sense of achievement and wonder.', '2030-01-13'),
                                                                        (18, 23, 'Autumn Aura IV', 'The autumn aura casts a spell of enchantment over the landscape.', '2030-02-25'),
                                                                        (19, 24, 'Misty Meadows IV', 'The misty meadows evoke a sense of mystery and wonder.', '2030-03-10');

INSERT INTO review (trail_id, user_id, title, content, review_date) VALUES
                                                                        (31, 36, 'Enchanted Falls III', 'The enchanting falls never ceased to captivate the imagination.', '2031-04-12'),
                                                                        (32, 37, 'Sapphire Summit III', 'Conquering Sapphire Summit again was a testament to perseverance.', '2031-05-25'),
                                                                        (1, 38, 'A Trail to Remember III', 'Memories created on this trail were etched into the soul forever.', '2031-06-07'),
                                                                        (2, 39, 'Sunset Beauty III', 'Sunset beauty on this trail was a painting come to life.', '2031-07-20'),
                                                                        (3, 40, 'Hidden Gem III', 'The hidden gem of waterfalls remained a treasure to behold.', '2031-08-02'),
                                                                        (4, 41, 'Mystical Adventure III', 'Every step on this mystical adventure felt like a journey within.', '2031-09-15'),
                                                                        (5, 42, 'Wildflower Wonderland III', 'The wonder of wildflowers continued to inspire awe and wonder.', '2031-10-28'),
                                                                        (6, 43, 'Alpine Beauty III', 'Returning to alpine landscapes felt like returning home.', '2031-11-10'),
                                                                        (7, 44, 'Scenic Lakes III', 'Scenic lakes provided moments of serenity amidst nature''s grandeur.', '2031-12-23'),
                                                                        (8, 45, 'Golden Meadows III', 'Golden meadows remained a beacon of tranquility and peace.', '2032-01-05'),
                                                                        (9, 46, 'Eagle''s Peak Summit III', 'Reaching the summit of Eagle''s Peak was a triumph of spirit.', '2032-02-18'),
                                                                        (10, 47, 'Serenity at Sunrise III', 'Sunrise serenity on this trail continued to stir the soul.', '2032-03-02'),
                                                                        (11, 48, 'Whispering Pines III', 'The whispering pines held secrets of nature''s wisdom.', '2032-04-15'),
                                                                        (12, 49, 'Winter Adventure III', 'Winter adventure brought a sense of exhilaration and wonder.', '2032-05-28');
